import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1435,height:940},reducedMotion:'reduce'});const errors=[],writes=[];let confirmAttempts=0;page.on('pageerror',e=>errors.push(e.message));
 const proposal={id:'p1',revision:1,family:'mcp-action',state:'pending',object:{id:'mcp1',name:'文档检索'},preview:{path:'C:/mock/config.toml',before_enabled:null,after_enabled:false,backup_location:'C:/mock/backups'}};
 let session={id:'s1',title:'检查连接配置',mode:'readonly',draft:'',target:null,messages:[{id:'u1',role:'user',text:'检查文档检索配置，先给我预览。'},{id:'a1',role:'assistant',mode:'readonly',run_id:'r1',text:'## 已核对配置\n文档检索当前启用。以下提案等待你的确认。',proposals:[proposal]}]};
 let run={id:'r1',session_id:'s1',status:'awaiting_confirmation',answer:session.messages[1].text,proposals:[proposal],usage:{total_tokens:83}};
 const events=[{seq:1,type:'text',channel:'intermediate',round_id:1,text:'先核对所选对象的配置摘要。'},{seq:2,type:'tool_started',round_id:1,call_id:'call1',name:'read_config_summary',arguments:{object_id:'mcp1'}},{seq:3,type:'tool_finished',round_id:1,call_id:'call1',name:'read_config_summary',ok:true,result:{kind:'配置摘要',enabled:true,source:'已登记清单'}},{seq:4,type:'final_answer',text:run.answer}];
 await page.addInitScript(()=>localStorage.setItem('desk-assistant-session','s1'));
 await page.route('**/api/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname;if(req.method()!=='POST')return route.continue();const b=req.postDataJSON();let result;if(path.endsWith('/model/settings'))result={config:{endpoint:'https://mock.invalid',model:'mock'}};else if(path.endsWith('/assistant/list'))result={sessions:[session]};else if(path.endsWith('/assistant/get'))result={session};else if(path.endsWith('/assistant/actions'))result={actions:[]};else if(path.endsWith('/run/get'))result={run,events:events.filter(e=>e.seq>(b.after||0))};else if(path.endsWith('/agent/confirm')||path.endsWith('/agent/reject')){if(path.endsWith('/confirm')&&confirmAttempts++===0)return route.fulfill({status:409,json:{error:'配置已变化，请重新核对提案。'}});writes.push({path,b});assert.equal(b.session_id,'s1');assert.equal(b.proposal_id,'p1');proposal.state=path.endsWith('/confirm')?'applied':'rejected';session={...session,messages:[...session.messages,{id:'receipt',role:'assistant',mode:'readonly',kind:'action_result',run_id:'r1',text:'配置修改已完成。'}]};result={proposal,session,run}}else return route.fulfill({status:400,json:{error:'unexpected '+path}});return route.fulfill({json:result})});
 await page.goto('http://127.0.0.1:8765');await page.getByRole('button',{name:'归处助手',exact:true}).click();await expect(page.getByRole('heading',{name:'已核对配置'})).toBeVisible();await expect(page.locator('.assistant-messages').getByText('先核对所选对象的配置摘要。',{exact:true})).toHaveCount(0);assert.equal(writes.length,0);
 const process=page.locator('.execution-process').first();await process.locator('.execution-disclosure').click();await expect(process.getByText('先核对所选对象的配置摘要。',{exact:true})).toBeVisible();await process.locator('summary').click();await expect(process.getByText('返回内容',{exact:true})).toBeVisible();await expect(process.locator('pre').last()).toContainText('已登记清单');await page.screenshot({path:'test-results/agent-process-1435.png'});await process.locator('.execution-disclosure').click();await expect(page.getByRole('heading',{name:'已核对配置'})).toBeVisible();await page.screenshot({path:'test-results/agent-process-final-1435.png'});await page.getByRole('button',{name:'确认执行',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'配置已变化'})).toBeVisible();assert.equal(writes.length,0);await page.getByRole('button',{name:'确认执行',exact:true}).click();await expect(page.getByText('配置修改已完成。',{exact:true})).toBeVisible();assert.equal(writes.length,1);await expect(page.getByRole('button',{name:'确认执行',exact:true})).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/agent-process-390.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);proposal.state='pending';session={...session,messages:session.messages.filter(m=>m.id!=='receipt')};await page.setViewportSize({width:1435,height:940});await page.reload();await page.getByRole('button',{name:'归处助手',exact:true}).click();await page.getByRole('button',{name:'拒绝这项提案',exact:true}).click();await expect(page.locator('.agent-proposal').getByText('已拒绝',{exact:true})).toBeVisible();assert.equal(writes.at(-1).path,'/api/agent/reject');proposal.state='pending';proposal.operation='restore';await page.reload();await page.getByRole('button',{name:'归处助手',exact:true}).click();await expect(page.getByRole('button',{name:'确认恢复',exact:true})).toBeVisible();const card=page.locator('.agent-proposal');await expect(card.locator('dl div').filter({has:page.locator('dt',{hasText:'修改前'})})).toContainText('停用');await expect(card.locator('dl div').filter({has:page.locator('dt',{hasText:'修改后'})})).toContainText('启用（默认）');assert.deepEqual(errors,[]);console.log('PASS collapsed process, recorded tool input/result, final answer retained, explicit bound confirm, mobile bounds; all writes mocked');
}finally{await browser.close()}
