import {toggleAppearance} from './theme-helpers.mjs';
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
fs.mkdirSync('test-results',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce'});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765');await page.locator('.agent-row').first().waitFor();
await page.screenshot({path:'test-results/desktop.png',fullPage:true});
await toggleAppearance(page);await page.screenshot({path:'test-results/dark.png',fullPage:true});await toggleAppearance(page);
await page.locator('.agent-row').first().click();await page.locator('.object-preview').click();await page.getByRole('button',{name:/关联 \d/}).click();assert(await page.locator('.relation-row').count()>0);
await page.getByRole('button',{name:'关闭详情'}).click();await page.locator('.object-drawer').waitFor({state:'hidden'});await page.keyboard.press('Control+k');await page.getByRole('textbox',{name:'搜索所有对象'}).fill('tavily');assert(await page.locator('.command-results button').count()>0);await page.locator('.command-results button').first().click();await page.locator('.command-dialog').waitFor({state:'hidden'});await page.locator('.object-preview').click();
await page.getByRole('button',{name:'备注',exact:true}).click();await page.getByLabel('备注',{exact:true}).fill('浏览器验证草稿');await page.getByRole('button',{name:'关闭详情'}).click();await page.locator('.object-drawer').waitFor({state:'hidden'});
await page.locator('.nav-item').filter({hasText:'技能与连接'}).click();await page.getByRole('textbox',{name:'搜索当前列表'}).fill('no_such_object_123');await page.getByRole('heading',{name:'没有找到匹配对象'}).waitFor();await page.getByRole('button',{name:'清除筛选'}).click();
await page.locator('.nav-item').filter({hasText:'工作台'}).click();await page.locator('.agent-row').first().click();await page.locator('.object-preview').click();await page.getByRole('button',{name:'备注',exact:true}).click();
const testNote='MVP 自动化验证 '+Date.now();
const initial=await page.evaluate(async()=>{const s=await(await fetch('/api/state')).json();return {id:s.data.objects.find(o=>o.kind==='agent').id,notes:s.data.notes,token:s.token}});
await page.getByRole('combobox',{name:'处理意向'}).click();await page.getByRole('option',{name:'保留',exact:true}).click();await page.getByLabel('备注',{exact:true}).fill(testNote);await page.getByRole('button',{name:'保存备注'}).click();await page.getByRole('status').filter({hasText:'已保存'}).waitFor();await page.reload();await page.locator('.agent-row').first().click();await page.locator('.object-preview').click();await page.getByRole('button',{name:'备注',exact:true}).click();assert.equal(await page.getByLabel('备注',{exact:true}).inputValue(),testNote);
await page.getByRole('button',{name:'关闭详情'}).click();await page.locator('.object-drawer').waitFor({state:'hidden'});await page.getByRole('button',{name:'刷新检查'}).click();await page.waitForFunction(async()=>!(await(await fetch('/api/state')).json()).scan.running);assert.equal(await page.evaluate(async(id)=>(await(await fetch('/api/state')).json()).data.notes[id].body,initial.id),testNote);
await page.evaluate(async({id,notes,token})=>{await fetch('/api/note',{method:'POST',headers:{'Content-Type':'application/json','X-Desk-Token':token},body:JSON.stringify({id,decision:notes[id]?.decision||'未标记',body:notes[id]?.body||''})});sessionStorage.clear() },initial);
await page.locator('.agent-row').first().click();await page.locator('.object-preview').click();await page.getByRole('button',{name:'概览',exact:true}).click();await page.screenshot({path:'test-results/detail.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'关闭详情'}).click();await page.locator('.object-drawer').waitFor({state:'hidden'});await page.screenshot({path:'test-results/mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'打开导航'}).click();await page.locator('.nav-item').filter({hasText:'目录地图'}).click();await page.getByRole('button',{name:/^查看 .* 详情$/}).first().click();await page.locator('.object-preview').click();await page.screenshot({path:'test-results/mobile-detail.png',fullPage:true});
await page.route('**/api/**',r=>r.abort());await page.reload();await page.getByRole('alert').waitFor();assert(await page.getByRole('button',{name:'刷新检查'}).isDisabled());
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: desktop/dark/mobile, search, relations, empty, note persistence, rescan, offline, no page errors');
