import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const page=await browser.newPage();
let failList=true,failSave=false,delay=false;
await page.route('**/api/assistant/list',r=>failList?r.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'读取测试失败'})}):r.continue());
await page.route('**/api/assistant/update',async r=>{if(failSave)return r.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'保存测试失败'})});if(delay)await new Promise(resolve=>setTimeout(resolve,1000));return r.continue()});
await page.goto('http://127.0.0.1:8765');await page.locator('.nav-item').filter({hasText:'归处助手'}).click();await page.getByRole('alert').filter({hasText:'读取测试失败'}).waitFor();failList=false;await page.getByRole('button',{name:'重试',exact:true}).click();await page.getByRole('button',{name:'新对话',exact:true}).click();
const api=async(action,body={})=>page.evaluate(async({action,body})=>{const s=await(await fetch('/api/state')).json();return(await fetch('/api/assistant/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Desk-Token':s.token},body:JSON.stringify(body)})).json()},{action,body});
await page.waitForFunction(()=>localStorage.getItem('desk-assistant-session'));const id=await page.evaluate(()=>localStorage.getItem('desk-assistant-session'));
try{failSave=true;await page.getByLabel('给助手的请求').fill('失败后保留草稿');await page.getByRole('alert').filter({hasText:'保存测试失败'}).waitFor();assert.equal(await page.getByLabel('给助手的请求').inputValue(),'失败后保留草稿');failSave=false;await page.getByRole('button',{name:'重试',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.assistant-history-heading')?.textContent.includes('已保存到本机'));assert.equal((await api('get',{id})).session.draft,'失败后保留草稿');delay=true;await page.getByLabel('给助手的请求').fill('第一段');await page.waitForFunction(()=>document.querySelector('.assistant-history-heading')?.textContent.includes('正在保存'));assert(await page.getByLabel('给助手的请求').isEnabled());await page.getByLabel('给助手的请求').fill('第一段与继续输入');await page.waitForFunction(()=>document.querySelector('.assistant-history-heading')?.textContent.includes('已保存到本机'));assert.equal((await api('get',{id})).session.draft,'第一段与继续输入');console.log('PASS initialization retry, failed save retains draft, typing during autosave persists latest input');}finally{delay=false;failSave=false;await api('delete',{id});await browser.close()}
