import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1304,height:884},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));const created=[];
await page.goto('http://127.0.0.1:8765');await page.locator('.nav-item').filter({hasText:'归处助手'}).click();
const api=async(action,body={})=>page.evaluate(async({action,body})=>{const s=await(await fetch('/api/state')).json();return(await fetch('/api/assistant/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Desk-Token':s.token},body:JSON.stringify(body)})).json()},{action,body});
const initial=(await api('list')).sessions.map(s=>s.id);
try{
 await page.getByRole('button',{name:'新对话',exact:true}).click();await page.getByLabel('给助手的请求').fill('历史验证 A '+Date.now());await page.getByRole('button',{name:'发送请求'}).click();await page.getByRole('button',{name:'体验确认流程'}).waitFor();let a=(await api('list')).sessions.find(s=>!initial.includes(s.id));created.push(a.id);
 await page.getByRole('button',{name:/历史对话/}).click();await page.getByRole('button',{name:'重命名 '+a.title,exact:true}).click();await page.getByLabel('对话标题').fill('验收会话 A');await page.getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('button',{name:'新对话',exact:true}).click();await page.getByLabel('给助手的请求').fill('第二会话独立草稿');await page.waitForFunction(()=>document.querySelector('.assistant-history-heading')?.textContent.includes('已保存到本机'));
 const b=(await api('list')).sessions.find(s=>!initial.includes(s.id)&&s.id!==a.id);created.push(b.id);await page.locator('.nav-item').filter({hasText:'工作台'}).click();await page.locator('.nav-item').filter({hasText:'归处助手'}).click();assert.equal(await page.getByLabel('给助手的请求').inputValue(),'第二会话独立草稿');await page.reload();await page.locator('.nav-item').filter({hasText:'归处助手'}).click();await page.waitForFunction(()=>document.querySelector('textarea[aria-label="给助手的请求"]')?.value==='第二会话独立草稿');
 await page.getByRole('button',{name:/历史对话/}).click();await page.getByLabel('搜索历史对话').fill('验收会话 A');await page.locator('.assistant-history-open').filter({hasText:'验收会话 A'}).click();assert((await page.locator('.assistant-message.user').textContent()).includes('历史验证 A'));assert.equal(await page.getByLabel('给助手的请求').inputValue(),'');await page.getByRole('button',{name:/历史对话/}).click();await page.getByLabel('搜索历史对话').fill('');await page.screenshot({path:'test-results/history-desktop.png'});
 await page.getByRole('button',{name:'删除 验收会话 A',exact:true}).click();await page.getByRole('button',{name:'确认删除',exact:true}).click();await page.waitForFunction(()=>!Array.from(document.querySelectorAll('.assistant-history-open')).some(e=>e.textContent.includes('验收会话 A')));await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/history-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 console.log('PASS history create/send/rename/search/delete, independent draft, navigation and reload persistence');
}finally{for(const id of created)await api('delete',{id});await browser.close()}
