import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,History,LoaderCircle,RotateCcw} from 'lucide-react';
import './action-panel.css';

const decisions=['未标记','保留','待确认'];
const states={pending:'待确认',applied:'已执行',conflict:'执行冲突',restored:'已恢复',restore_conflict:'恢复冲突'};
const decisionOf=note=>note?.decision||'未标记';

export default function ActionPanel({object,post,onChanged,offline=false,setBusy:setParentBusy,origin,onOpenSession}){
 const [decision,setDecision]=useState(''),[actions,setActions]=useState([]),[selected,setSelected]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false);
 const generation=useRef(0),locked=useRef(false),postRef=useRef(post),request=useRef(null),objectId=object?.id;
 postRef.current=post;
 const action=actions.find(item=>item.id===selected),disabled=!!busy||offline||!loaded||!objectId;
 function belongs(item,id){return item.object?.id===id||item.object_id===id}
 async function readHistory(epoch,id){const result=await postRef.current('action/list',{});if(generation.current===epoch){setActions((result.actions||[]).filter(item=>belongs(item,id)));setLoaded(true)}}
 async function perform(kind,work){if(locked.current||!objectId||offline)return;const epoch=generation.current,id=objectId;locked.current=true;setBusy(kind);setParentBusy?.(true);setError('');setNotice('');try{await work(epoch,id)}catch(e){if(generation.current===epoch)setError(e.message||'操作未完成，请重试。')}finally{if(generation.current===epoch){locked.current=false;setBusy('');setParentBusy?.(false)}}}
 useEffect(()=>{const epoch=++generation.current;locked.current=false;setActions([]);setSelected(null);setDecision('');setError('');setNotice('');setLoaded(false);request.current=null;if(objectId)perform('load',(token,id)=>readHistory(token,id));return()=>{if(generation.current===epoch){generation.current++;setParentBusy?.(false)}}},[objectId]);
 useEffect(()=>{if(!offline&&!loaded&&!locked.current&&objectId)perform('load',(epoch,id)=>readHistory(epoch,id))},[offline]);
 useEffect(()=>{request.current=null},[origin?.session_id,origin?.run_id]);
 function propose(){if(disabled||!decision)return;perform('propose',async(epoch,id)=>{if(!request.current||request.current.objectId!==id||request.current.decision!==decision)request.current={objectId:id,decision,id:crypto.randomUUID()};const result=await postRef.current('action/propose',{object_id:id,decision,request_id:request.current.id,...(origin?{origin}:{})});if(generation.current!==epoch)return;const proposal=result.action||result.proposal||result;setActions(previous=>[proposal,...previous.filter(item=>item.id!==proposal.id)]);setSelected(proposal.id);request.current=null;setNotice('提案已生成，确认后才会更新工作台标记。')})}
 function apply(kind,item){perform(kind,async(epoch,id)=>{try{const result=await postRef.current('action/'+kind,{id:item.id,revision:item.revision});if(generation.current!==epoch)return;const updated=result.action||result;setActions(previous=>previous.map(existing=>existing.id===updated.id?updated:existing));setSelected(updated.id);setNotice(kind==='confirm'?'工作台标记已更新。':'工作台标记已恢复到执行前。');await readHistory(epoch,id);await onChanged?.(id)}catch(e){try{await readHistory(epoch,id)}catch{}throw e}})}
 return <section className="detail-section action-panel" aria-labelledby="action-panel-title"><h3 id="action-panel-title">保留决定</h3><p className="muted">先预览，再确认。仅更新工作台内的保留标记，不修改软件、配置或电脑文件。</p>
 {!objectId?<p className="muted">请先选择一个对象。</p>:<><div className="action-decision-options" role="group" aria-label="选择保留决定">{decisions.map(value=><button type="button" key={value} disabled={disabled} aria-pressed={decision===value} onClick={()=>{setDecision(value);setNotice('')}}>{value}</button>)}</div><button type="button" className="button" disabled={disabled||!decision} onClick={propose}>{busy==='propose'?<LoaderCircle size={15} className="spin"/>:<ArrowRight size={15}/>}生成标记提案</button>
 {offline&&<p className="action-feedback" role="status">本地服务离线，标记修改与恢复暂不可用。</p>}{busy==='load'&&<p className="action-feedback" role="status">正在读取标记记录…</p>}{error&&<div className="action-feedback action-error" role="alert"><span>{error}</span><button type="button" className="text-button" disabled={!!busy||offline} onClick={()=>perform('load',(epoch,id)=>readHistory(epoch,id))}>重新读取记录</button></div>}{notice&&<p className="action-feedback" role="status">{notice}</p>}
 {action&&<div className="action-preview" aria-label="标记变更预览"><div className="action-preview-heading"><strong>{action.object?.name||object.name}</strong><span>{states[action.state]||action.state}</span></div>{action.origin?.session_id&&<div className="operation-origin"><p className="muted">来源对话：{action.origin.title||'未命名对话'}</p>{onOpenSession&&<button type="button" className="text-button" disabled={!!busy||offline} onClick={()=>onOpenSession(action.origin.session_id)}>返回来源对话<ArrowRight size={14}/></button>}</div>}<dl className="action-diff"><div><dt>执行前</dt><dd>{decisionOf(action.before)}</dd></div><ArrowRight size={16} aria-hidden="true"/><div><dt>执行后</dt><dd>{decisionOf(action.after)}</dd></div></dl>{action.state==='pending'&&<><p className="muted">确认时会再次核对当前标记。其他操作已改变标记时，需要重新生成提案。</p><button type="button" className="button primary" disabled={!!busy||offline} onClick={()=>apply('confirm',action)}>{busy==='confirm'?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>}确认更新标记</button></>}{action.state==='applied'&&<><p className="muted">已完成工作台标记更新。恢复前会核对当前记录，避免覆盖后续修改。</p><button type="button" className="button" disabled={!!busy||offline} onClick={()=>apply('restore',action)}>{busy==='restore'?<LoaderCircle size={15} className="spin"/>:<RotateCcw size={15}/>}恢复执行前标记</button></>}{['conflict','restore_conflict'].includes(action.state)&&<p className="action-feedback" role="status">当前记录已发生变化，未覆盖后续修改。请核对当前记录后重新生成提案。</p>}{action.state==='restored'&&<p className="muted">已恢复执行前的工作台标记。</p>}</div>}
 <details className="action-history"><summary><History size={14}/>标记历史 · {actions.length}</summary>{loaded&&!actions.length?<p className="muted">此对象还没有标记操作记录。</p>:<div>{actions.map(item=><button type="button" key={item.id} className="action-history-item" aria-current={selected===item.id?'true':undefined} disabled={!!busy} onClick={()=>{setSelected(item.id);setNotice('')}}><span>{decisionOf(item.before)} → {decisionOf(item.after)}</span><small>{states[item.state]||item.state}</small></button>)}</div>}</details></>}
 </section>
}
