import React,{useRef,useState} from 'react';
const states={pending:'待确认',applied:'已执行',conflict:'内容已变化，未执行',rejected:'已拒绝',failed:'执行失败',restored:'已恢复',restore_conflict:'恢复冲突，未覆盖',interrupted:'执行中断'};
const decision=value=>value?.decision||'未标记';
export default function AgentProposal({proposal,sessionId,post,disabled,onResult}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[updated,setUpdated]=useState(null),request=useRef(crypto.randomUUID());
 const p=updated||proposal,a=p.preview||{},claude=p.family==='claude-action',batch=p.family==='category-action',mcp=p.family==='mcp-action'||p.family==='claude-action',restore=p.operation==='restore';
 const before=restore?a.after:a.before,after=restore?a.before:a.after,beforeEnabled=restore?a.after_enabled:a.before_enabled,afterEnabled=restore?a.before_enabled:a.after_enabled;
 async function resolve(accept){if(busy||disabled)return;setBusy(true);setError('');try{const result=await post(accept?'agent/confirm':'agent/reject',{session_id:sessionId,proposal_id:p.id,revision:p.revision,request_id:request.current});setUpdated(result.proposal);onResult(result,sessionId)}catch(e){setError(e.message||'操作未完成，请核对记录后重试。');try{const latest=await post('assistant/get',{id:sessionId});const saved=latest.session.messages.flatMap(m=>m.proposals||[]).find(item=>item.id===p.id);if(saved)setUpdated(saved);onResult(latest,sessionId)}catch{}}finally{setBusy(false)}}
 return <section className="agent-proposal" aria-label="变更提案"><h3>{restore?'恢复此前变更':claude?'移除 Claude MCP 注册':batch?'批量调整软件分类':mcp?'修改 MCP 启用状态':'更新保留决定'} · {p.object?.name||a.object?.name||'对象'}</h3><dl>{(a.path||p.object?.path)&&<div><dt>位置</dt><dd>{a.path||p.object.path}</dd></div>}{!batch&&<><div><dt>修改前</dt><dd>{claude?(beforeEnabled===false?'已移除':'已注册'):mcp?(beforeEnabled===false?'停用':beforeEnabled==null?'启用（默认）':'启用'):decision(before)}</dd></div><div><dt>修改后</dt><dd>{claude?(afterEnabled===false?'移除注册':'恢复注册'):mcp?(afterEnabled===false?'停用':afterEnabled==null?'启用（默认）':'启用'):decision(after)}</dd></div></>}{batch&&(a.targets||[]).map(t=><div key={t.id}><dt>{t.name}</dt><dd>{before?.[t.id]?.[0]||'自动分类'} → {after?.[t.id]?.[0]||'自动分类'}</dd></div>)}{a.backup_location&&<div><dt>备份</dt><dd>{a.backup_location}</dd></div>}<div><dt>状态</dt><dd>{states[p.state]||p.state}</dd></div></dl><p>{batch?'整批写入归处内部分类；任一对象发生冲突时整批不执行。':claude?(restore?'恢复原始配置；后续配置有变化时不会覆盖。':'从 Claude Code 用户配置移除此 MCP 注册并保存备份；不会卸载服务。JSON 将统一缩进，其他配置值保留。当前会话可能需要重启。'):mcp?(restore?'确认后恢复此前配置；当前会话可能需要重启才能生效。':'确认后修改所列配置并备份；当前会话可能需要重启才能生效。'):'仅修改归处中的保留标记，不卸载软件或删除文件。'}</p>{p.state==='pending'&&<div className="agent-proposal-actions"><button type="button" className="button primary" disabled={disabled||busy} onClick={()=>resolve(true)}>{busy?'正在处理…':restore?'确认恢复':'确认执行'}</button><button type="button" className="button" disabled={disabled||busy} onClick={()=>resolve(false)}>拒绝这项提案</button></div>}{error&&<p role="alert">{error}</p>}</section>;
}
