import React,{useEffect,useRef,useState,useId} from 'react';
import {ArrowRight,Check,History,LoaderCircle,RefreshCw} from 'lucide-react';
import './cleanup-panel.css';

const states={pending:'待确认',executing:'正在执行',recycled:'已移到回收站',failed:'执行失败',interrupted:'执行中断',conflict:'目标已变化',waiting_user:'等待你完成官方卸载',removed:'注册状态已移除',still_registered:'仍有卸载注册记录'};
const formatBytes=value=>Number.isFinite(value)?`${value.toLocaleString('zh-CN')} 字节`:'未记录';

export default function CleanupPanel({object,post,offline=false,onChanged,setBusy:setParentBusy,historyOnly=false,origin,onOpenSession}){
 const titleId=useId();
 const [actions,setActions]=useState([]),[selected,setSelected]=useState(null),[acknowledged,setAcknowledged]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const epoch=useRef(0),locked=useRef(false),postRef=useRef(post),request=useRef(null),objectId=historyOnly?'*':object?.id;
 postRef.current=post;
 const action=actions.find(item=>item.id===selected);
 const kind=historyOnly?action?.kind:object?.kind==='directory'?'recycle':object?.kind==='software'?'uninstall':null;
 const working=actions.some(item=>item.state==='executing'),disabled=!!busy||offline||!loaded||!kind||working;
 const preview=action?.preview||action||{};
 async function read(token,id){const result=await postRef.current('cleanup/list',{});if(token===epoch.current){setActions((result.actions||[]).filter(item=>historyOnly||(item.object?.id||item.object_id)===id));setLoaded(true)}}
 async function perform(label,work){if(locked.current||offline||(!kind&&!historyOnly))return;const token=epoch.current,id=objectId;locked.current=true;setBusy(label);setParentBusy?.(true);setError('');setNotice('');try{await work(token,id)}catch(e){if(token===epoch.current)setError(e.message||'请求未完成，请重新读取记录核对状态。')}finally{if(token===epoch.current){locked.current=false;setBusy('');setParentBusy?.(false)}}}
 useEffect(()=>{const token=++epoch.current;locked.current=false;request.current=null;setActions([]);setSelected(null);setAcknowledged(false);setLoaded(false);setBusy('');setError('');setNotice('');if(kind||historyOnly)perform('load',read);return()=>{if(token===epoch.current){epoch.current++;setParentBusy?.(false)}}},[objectId]);
 useEffect(()=>{if(!offline&&!loaded&&!locked.current&&(kind||historyOnly))perform('load',read)},[offline]);
 useEffect(()=>{request.current=null},[origin?.session_id,origin?.run_id]);
 function propose(){if(disabled)return;perform('propose',async(token,id)=>{if(!request.current)request.current=crypto.randomUUID();const result=await postRef.current('cleanup/propose',{object_id:id,kind,request_id:request.current,...(origin?{origin}:{})});if(token!==epoch.current)return;setActions(previous=>[result.action,...previous.filter(item=>item.id!==result.action.id)]);setSelected(result.action.id);setAcknowledged(false);request.current=null;setNotice('提案已生成，尚未执行。请核对范围后确认。')})}
 function operate(route,item){if(disabled||route==='confirm'&&!acknowledged)return;perform(route,async(token,id)=>{try{const body=route==='confirm'?{id:item.id,revision:item.revision,acknowledge:true}:{id:item.id};const result=await postRef.current('cleanup/'+route,body);if(token!==epoch.current)return;setActions(previous=>previous.map(existing=>existing.id===result.action.id?result.action:existing));setSelected(result.action.id);setAcknowledged(false);await read(token,id);await onChanged?.(id)}catch(e){try{await read(token,id)}catch{}throw e}})}
 return <section className="detail-section cleanup-panel" aria-labelledby={titleId}><h3 id={titleId}>{historyOnly?'清理操作记录':kind==='recycle'?'目录回收':'官方软件卸载'}</h3>{!kind&&!historyOnly?<p className="muted">请选择目录或已登记的软件对象。</p>:<>
 {!historyOnly&&<><p className="muted">{kind==='recycle'?'先检查所选目录的精确范围与使用情况，再决定是否移到 Windows 回收站。':'仅支持可核验的 Windows MSI 产品。这里只启动官方交互卸载流程，需要你在系统窗口中继续操作。'}</p><button type="button" className="button" disabled={disabled} onClick={propose}>{busy==='propose'?<LoaderCircle size={15} className="spin"/>:<ArrowRight size={15}/>} {kind==='recycle'?'预览回收范围':'预览官方卸载'}</button></>}{historyOnly&&<p className="muted">保留执行时的对象与范围快照。对象从清单消失后，仍可在此核对结果。</p>}
 {offline&&<p className="cleanup-feedback" role="status">本地服务离线，暂不可预览或执行。</p>}{busy==='load'&&<p className="cleanup-feedback" role="status">正在读取操作记录…</p>}{error&&<div className="cleanup-feedback cleanup-error" role="alert">{error}</div>}{notice&&<p className="cleanup-feedback" role="status">{notice}</p>}
 {action&&<div className="cleanup-preview" aria-label="清理操作提案"><div className="cleanup-preview-heading"><strong>{action.object?.name||object?.name||'历史对象'}</strong><span>{states[action.state]||action.state}</span></div>{action.origin?.session_id&&<div className="operation-origin"><p className="muted">来源对话：{action.origin.title||'未命名对话'}</p>{onOpenSession&&<button type="button" className="text-button" disabled={!!busy||offline} onClick={()=>onOpenSession(action.origin.session_id)}>返回来源对话<ArrowRight size={14}/></button>}</div>}
 {kind==='recycle'?<><div className="cleanup-path"><span>精确目录范围</span><code>{preview.path||action.path||object?.path||'未记录'}</code></div><dl className="cleanup-scope-counts"><div><dt>文件</dt><dd>{Number.isFinite(preview.files)?preview.files:'未记录'}</dd></div><div><dt>目录</dt><dd>{Number.isFinite(preview.directories??preview.dirs)?preview.directories??preview.dirs:'未记录'}</dd></div><div><dt>文件逻辑大小</dt><dd>{formatBytes(preview.bytes)}</dd></div></dl><p className="cleanup-usage">使用检查：{preview.usage_check==='complete'?'已完成可用进程的程序路径与工作目录检查。':preview.usage_check==='partial'?'部分进程信息无法读取，使用检查不完整。':'使用检查结果未记录。'} 该检查不覆盖全部文件句柄，未发现占用不代表目录未被使用。</p><p className="cleanup-boundary">移入 Windows 回收站后，只能尝试在系统回收站手动恢复；回收站策略、容量和后续清空可能使恢复不可用。这里不提供永久删除或自动恢复。</p></>:<><div className="cleanup-path"><span>官方卸载方式</span><strong>Windows MSI 交互卸载</strong>{(preview.product_code||preview.productCode||action.product_code)&&<code>{preview.product_code||preview.productCode||action.product_code}</code>}</div>{preview.installer_path&&<div className="cleanup-path"><span>官方卸载入口</span><code>{preview.installer_path}</code></div>}{preview.usage_note&&<p className="cleanup-usage">{preview.usage_note}</p>}<p className="cleanup-boundary">确认后打开官方卸载程序，由你在系统窗口中继续或取消。卸载不保证可恢复；结束后需重新核对注册状态。</p></>}
 {action.state==='pending'&&!historyOnly&&<><label className="cleanup-acknowledge"><input type="checkbox" checked={acknowledged} disabled={disabled} onChange={event=>setAcknowledged(event.target.checked)}/>{kind==='recycle'?'我已关闭相关程序并核对范围。':'我已关闭相关程序、核对软件身份，了解卸载不保证恢复。'}</label><button type="button" className="button primary" disabled={disabled||!acknowledged} onClick={()=>operate('confirm',action)}>{busy==='confirm'?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>} {kind==='recycle'?'确认移到回收站':'打开官方卸载程序'}</button></>}
 {['waiting_user','still_registered'].includes(action.state)&&<><p className="cleanup-feedback">请在官方卸载窗口完成或取消操作，再回来核对。注册记录消失不代表所有文件都已清除。</p><button type="button" className="button" disabled={disabled} onClick={()=>operate('verify',action)}><RefreshCw size={14} className={busy==='verify'?'spin':''}/>重新核对注册状态</button></>}
 {kind==='recycle'&&['recycled','failed','interrupted'].includes(action.state)&&<><p className="cleanup-feedback">{action.state==='recycled'?'已移到 Windows 回收站。需要恢复时，请在系统回收站中手动查找该目录。':'执行结果可能不确定，请同时核对原位置与 Windows 回收站；需要恢复时在系统回收站手动操作。'}</p><button type="button" className="button" disabled={!!busy||offline} onClick={()=>perform('open-bin',async()=>{await postRef.current('cleanup/open-bin',{})})}>打开回收站</button></>}{action.state==='removed'&&<p className="cleanup-feedback">此次核对未发现该产品的卸载注册记录；不据此判断全部文件已清除。</p>}{['failed','interrupted'].includes(action.state)&&<p className="cleanup-feedback">操作未正常完成，请核对实际目录或软件状态。未确认发生自动回滚。</p>}{action.state==='conflict'&&<p className="cleanup-feedback">目标与提案不一致，请重新预览后再决定。</p>}{action.state==='executing'&&<p className="cleanup-feedback">操作正在执行，请刷新记录查看结果。</p>}{action.error&&<p className="cleanup-feedback">{typeof action.error==='string'?action.error:'操作遇到错误。'}</p>}</div>}
 <div className="cleanup-history-heading"><span><History size={14}/>操作历史 · {actions.length}</span><button type="button" className="text-button" disabled={!!busy||offline} onClick={()=>perform('load',read)}><RefreshCw size={13}/>刷新清理记录</button></div><details className="cleanup-history"><summary>{historyOnly?'查看全部清理操作':'查看此对象的历史操作'}</summary>{loaded&&!actions.length?<p className="muted">还没有操作记录。</p>:actions.map(item=><button type="button" key={item.id} className="cleanup-history-item" disabled={!!busy} aria-current={selected===item.id?'true':undefined} onClick={()=>{setSelected(item.id);setAcknowledged(false);setNotice('')}}><span>{historyOnly?(item.object?.name||item.path||'历史对象')+' · ':''}{item.kind==='recycle'?'目录回收':'官方卸载'}</span><small>{states[item.state]||item.state}</small></button>)}</details>
 </>}</section>
}

export function CleanupHistory(props){return <CleanupPanel {...props} historyOnly/>}
