import React,{useEffect,useRef,useState} from 'react';
import {Calculator,LoaderCircle,RefreshCw,Square} from 'lucide-react';
import './directory-size.css';

const active=task=>task&&['queued','running'].includes(task.status);
const statusText={queued:'等待统计',running:'正在统计',succeeded:'统计完成',partial:'部分结果',cancelled:'已停止',interrupted:'统计中断',failed:'统计失败'};
const normalized=path=>String(path||'').replaceAll('/','\\').replace(/[\\]+$/,'').toLowerCase();
function size(bytes){if(bytes<1024)return bytes+' B';if(bytes<1024**2)return(bytes/1024).toFixed(1)+' KiB';if(bytes<1024**3)return(bytes/1024**2).toFixed(1)+' MiB';return(bytes/1024**3).toFixed(2)+' GiB'}

export default function DirectorySize({path,post,offline=false}){
 const [task,setTask]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const epoch=useRef(0),postRef=useRef(post),lock=useRef(false),request=useRef(null),previousOffline=useRef(offline);
 postRef.current=post;
 async function history(token=epoch.current,target=path){setLoading(true);setError('');try{const result=await postRef.current('size/list',{});if(token!==epoch.current)return;const tasks=(result.tasks||[]).filter(item=>normalized(item.path)===normalized(target));tasks.sort((a,b)=>String(b.created_at||b.updated_at||'').localeCompare(String(a.created_at||a.updated_at||'')));setTask(tasks[0]||null)}catch(e){if(token===epoch.current)setError(e.message||'无法读取统计记录。')}finally{if(token===epoch.current)setLoading(false)}}
 useEffect(()=>{const token=++epoch.current;lock.current=false;request.current=null;setTask(null);setBusy('');setError('');setLoading(true);if(!offline)history(token,path);else setLoading(false);return()=>{if(epoch.current===token)epoch.current++}},[path]);
 useEffect(()=>{if(previousOffline.current&&!offline)history(epoch.current,path);previousOffline.current=offline},[offline]);
 useEffect(()=>{if(!active(task)||offline)return;const token=epoch.current,id=task.id,target=path;let stopped=false,timer;async function poll(){try{const result=await postRef.current('size/get',{id});if(stopped||token!==epoch.current)return;if(result.task.id!==id||normalized(result.task.path)!==normalized(target))throw Error('统计结果与当前目录不一致。');setTask(result.task);setError('');if(active(result.task))timer=setTimeout(poll,800)}catch(e){if(stopped||token!==epoch.current)return;setError(e.message||'读取统计进度失败，正在重连。');timer=setTimeout(poll,1800)}}poll();return()=>{stopped=true;clearTimeout(timer)}},[task?.id,offline]);
 async function operate(kind){if(lock.current||offline||loading)return;const token=epoch.current,target=path,id=task?.id;lock.current=true;setBusy(kind);setError('');try{let result;if(kind==='start'){if(!request.current)request.current=crypto.randomUUID();result=await postRef.current('size/start',{path:target,request_id:request.current})}else result=await postRef.current('size/cancel',{id});if(token!==epoch.current)return;if(normalized(result.task.path)!==normalized(target))throw Error('统计任务与当前目录不一致。');setTask(result.task);if(kind==='start')request.current=null}catch(e){if(token===epoch.current)setError(e.message||'请求未完成，请重试。')}finally{if(token===epoch.current){lock.current=false;setBusy('')}}}
 const running=active(task),incomplete=task&&task.status!=='succeeded',bytes=Number(task?.bytes)||0;
 return <section className="directory-size" aria-label="目录大小统计"><div className="directory-size-heading"><div><h3>目录大小</h3><p>按需递归统计文件逻辑大小，可继续浏览其他目录。</p></div>{running?<button type="button" className="button" disabled={offline||!!busy||task.cancel_requested} onClick={()=>operate('cancel')}>{busy==='cancel'?<LoaderCircle size={14} className="spin"/>:<Square size={13}/>} {task.cancel_requested?'正在停止':'停止统计'}</button>:<button type="button" className="button" disabled={offline||loading||!!busy} onClick={()=>operate('start')}>{busy==='start'?<LoaderCircle size={14} className="spin"/>:<Calculator size={15}/>} {task?['failed','interrupted','cancelled'].includes(task.status)?'重试统计':'重新统计':'统计目录大小'}</button>}</div>
 {loading&&!task&&<p className="directory-size-note" role="status">正在读取此目录的统计记录…</p>}{offline&&<p className="directory-size-note" role="status">本地服务离线，连接恢复后可继续查看统计。</p>}{error&&<div className="directory-size-error" role="alert"><span>{error}</span><button type="button" className="text-button" disabled={offline||loading||!!busy} onClick={()=>history()}><RefreshCw size={13}/>重新读取统计</button></div>}
 {task&&<><div className="directory-size-result" aria-live="polite"><div><span>{incomplete?'已统计逻辑大小':'逻辑大小'}</span><strong>{size(bytes)}</strong><small>{bytes.toLocaleString('zh-CN')} 字节</small></div><div className="directory-size-progress"><span>{running&&<LoaderCircle size={13} className="spin"/>}{statusText[task.status]||task.status}</span><p>已扫描 {task.files||0} 个文件 · {task.directories||0} 个目录</p></div></div>{incomplete&&!running&&<p className="directory-size-note">当前是部分结果，不代表整个目录的完整大小。{task.limit==='time'?'已达到统计时间限制。':task.limit==='entries'?'已达到条目数量限制。':task.limit?'已达到统计限制。':''}</p>}{(task.errors>0||task.skipped>0||task.hardlinks>0)&&<p className="directory-size-note">读取错误 {task.errors||0} 项 · 跳过 {task.skipped||0} 项{task.hardlinks>0?` · ${task.hardlinks} 个重复硬链接未重复计入字节`:''}</p>}{task.error&&<p className="directory-size-note" role="status">{task.error}</p>}{task.updated_at&&<p className="directory-size-note">记录更新于 {new Date(task.updated_at).toLocaleString('zh-CN')}</p>}</>}
 <p className="directory-size-scope">不读取文件内容，不跟随链接。重复硬链接不重复计入字节；逻辑大小不等于实际磁盘占用。</p></section>
}
