import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,History,LoaderCircle,RefreshCw,RotateCcw} from 'lucide-react';
import './mcp-action-panel.css';

const labels={pending:'待确认',applying:'正在修改',applied:'已修改',restoring:'正在恢复',restored:'已恢复',conflict:'配置冲突',failed:'操作失败',interrupted:'操作中断',restore_conflict:'恢复冲突'};
const observations={matches_before:'当前配置与执行前一致。',matches_after:'当前配置与拟议修改一致。',changed:'当前配置已出现其他变化。',unavailable:'暂时无法核验当前配置。'};
const enabledLabel=value=>value==null?'默认启用（未设置）':value?'启用':'停用';
const inProgress=item=>['applying','restoring'].includes(item.state);

export default function McpActionPanel({object,post,onChanged,offline=false,setBusy:setParentBusy,origin,onOpenSession,historyOnly=false,initialActionId}){
 const [enabled,setEnabled]=useState(null),[actions,setActions]=useState([]),[selected,setSelected]=useState(null),[busy,setBusy]=useState(''),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const generation=useRef(0),locked=useRef(false),postRef=useRef(post),request=useRef(null),objectId=object?.id;
 postRef.current=post;
 const eligible=object?.kind==='mcp'&&object.scope==='codex'&&object.source==='用户配置';
 const action=actions.find(item=>item.id===selected),changing=actions.some(inProgress),disabled=!!busy||offline||!loaded||!eligible||changing;
 async function readHistory(epoch,id){const result=await postRef.current('mcp-action/list',{});if(generation.current!==epoch)return;setActions((result.actions||[]).filter(item=>(item.object?.id||item.object_id)===id));setLoaded(true)}
 async function perform(kind,work){if(locked.current||offline||!eligible)return;const epoch=generation.current,id=objectId;locked.current=true;setBusy(kind);setParentBusy?.(true);setError('');setNotice('');try{await work(epoch,id)}catch(e){if(generation.current===epoch)setError(e.message||'操作未完成，请重新读取记录核对状态。')}finally{if(generation.current===epoch){locked.current=false;setBusy('');setParentBusy?.(false)}}}
 useEffect(()=>{const epoch=++generation.current;locked.current=false;setActions([]);setSelected(null);setEnabled(null);setLoaded(false);setBusy('');setError('');setNotice('');request.current=null;if(eligible)perform('load',readHistory);return()=>{if(generation.current===epoch){generation.current++;setParentBusy?.(false)}}},[objectId]);
 useEffect(()=>{if(!offline&&!loaded&&!locked.current&&eligible)perform('load',readHistory)},[offline]);
 useEffect(()=>{request.current=null},[origin?.session_id,origin?.run_id]);
 useEffect(()=>{if(loaded&&initialActionId&&actions.some(item=>item.id===initialActionId))setSelected(initialActionId)},[initialActionId,loaded,objectId]);
 function propose(){if(disabled||historyOnly||enabled===null)return;perform('propose',async(epoch,id)=>{if(!request.current||request.current.objectId!==id||request.current.enabled!==enabled)request.current={objectId:id,enabled,id:crypto.randomUUID()};const result=await postRef.current('mcp-action/propose',{object_id:id,enabled,request_id:request.current.id,...(origin?{origin}:{})});if(generation.current!==epoch)return;const proposal=result.action;setActions(previous=>[proposal,...previous.filter(item=>item.id!==proposal.id)]);setSelected(proposal.id);request.current=null;setNotice('配置提案已生成，尚未写入配置或创建执行备份。')})}
 function execute(kind,item){if(disabled)return;perform(kind,async(epoch,id)=>{try{const result=await postRef.current('mcp-action/'+kind,{id:item.id,revision:item.revision});if(generation.current!==epoch)return;const updated=result.action;setActions(previous=>previous.map(existing=>existing.id===updated.id?updated:existing));setSelected(updated.id);setNotice(updated.state==='applied'?'配置已修改，已保存执行记录。':updated.state==='restored'?'配置已恢复到执行前。':'请求已处理，请查看操作状态。');await readHistory(epoch,id);await onChanged?.(id)}catch(e){try{await readHistory(epoch,id)}catch{}throw e}})}
 return <section className="detail-section mcp-action-panel" aria-labelledby="mcp-action-title"><h3 id="mcp-action-title">Codex MCP 配置</h3>{!eligible?<p className="muted">此处仅支持 Codex 用户配置中的独立 MCP 条目。其他来源暂不可修改。</p>:<>
 {!historyOnly&&<><p className="muted">仅修改此条目的 enabled 字段。服务会校验是否为支持的独立配置表；不删除条目、不停止进程，也不保证当前 Codex 会话立即生效。</p>
 <div className="mcp-enabled-options" role="group" aria-label="选择 MCP 启用状态">{[[false,'停用'],[true,'启用']].map(([value,label])=><button type="button" key={label} disabled={disabled} aria-pressed={enabled===value} onClick={()=>{setEnabled(value);setNotice('')}}>{label}</button>)}</div>
 <button type="button" className="button" disabled={disabled||enabled===null} onClick={propose}>{busy==='propose'?<LoaderCircle size={15} className="spin"/>:<ArrowRight size={15}/>}生成配置提案</button></>}{historyOnly&&<p className="muted">查看执行时的配置范围与结果。恢复仍会核对当前文件，避免覆盖后续修改。</p>}
 {offline&&<p className="mcp-action-feedback" role="status">本地服务离线，配置修改与恢复暂不可用。</p>}{busy==='load'&&<p className="mcp-action-feedback" role="status">正在读取配置操作记录…</p>}{error&&<div className="mcp-action-feedback mcp-action-error" role="alert">{error}</div>}{notice&&<p className="mcp-action-feedback" role="status">{notice}</p>}
 {action&&<div className="mcp-action-preview" aria-label="MCP 配置变更预览"><div className="mcp-action-heading"><strong>{action.object?.name||object.name}</strong><span>{labels[action.state]||action.state}</span></div>{action.origin?.session_id&&<div className="operation-origin"><p className="muted">来源对话：{action.origin.title||'未命名对话'}</p>{onOpenSession&&<button type="button" className="text-button" disabled={!!busy||offline} onClick={()=>onOpenSession(action.origin.session_id)}>返回来源对话<ArrowRight size={14}/></button>}</div>}<dl className="mcp-action-diff"><div><dt>原 enabled</dt><dd>{enabledLabel(action.before_enabled)}</dd></div><ArrowRight size={16} aria-hidden="true"/><div><dt>新 enabled</dt><dd>{enabledLabel(action.after_enabled)}</dd></div></dl><div className="mcp-action-path"><span>目标配置</span><code>{action.path||'尚未记录'}</code></div><div className="mcp-action-path"><span>{action.receipt?'执行备份位置':'备份位置（确认执行时创建）'}</span><code>{action.backup_location||'尚未记录'}</code></div>
 {action.state==='pending'&&!historyOnly&&<><p className="muted">确认时会再次核对配置内容与目标条目。内容已变化时停止执行，需要重新生成提案。</p><button type="button" className="button primary" disabled={disabled} onClick={()=>execute('confirm',action)}>{busy==='confirm'?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>}确认修改配置</button></>}
 {inProgress(action)&&<p className="mcp-action-feedback" role="status">操作尚未完成，请刷新记录核对结果。</p>}
 {['conflict','restore_conflict'].includes(action.state)&&<p className="mcp-action-feedback" role="status">配置与预期不一致，本次操作未覆盖后续修改。请核对配置和记录。</p>}
 {['failed','interrupted'].includes(action.state)&&<p className="mcp-action-feedback" role="status">操作未正常完成。请查看执行记录与备份，核对实际配置状态。</p>}
 {action.observed_state&&observations[action.observed_state]&&<p className="mcp-action-feedback" role="status">{observations[action.observed_state]}</p>}
 {action.receipt&&['applied','failed','interrupted','restore_conflict'].includes(action.state)&&<><p className="muted">恢复使用此次执行备份，执行前会核对当前配置，避免覆盖后续修改。</p><button type="button" className="button" disabled={disabled} onClick={()=>execute('restore',action)}>{busy==='restore'?<LoaderCircle size={15} className="spin"/>:<RotateCcw size={15}/>}恢复原配置</button></>}
 {action.state==='restored'&&<p className="muted">已恢复执行前的配置；当前 Codex 会话可能仍需重新加载。</p>}</div>}
 <div className="mcp-action-history-heading"><span><History size={14}/>配置操作历史 · {actions.length}</span><button type="button" className="text-button" disabled={!!busy||offline} onClick={()=>perform('load',readHistory)}><RefreshCw size={13}/>刷新记录</button></div><details className="mcp-action-history"><summary>查看此对象的操作记录</summary>{loaded&&!actions.length?<p className="muted">还没有配置操作记录。</p>:actions.map(item=><button type="button" key={item.id} disabled={!!busy} className="mcp-action-history-item" aria-current={selected===item.id?'true':undefined} onClick={()=>{setSelected(item.id);setNotice('')}}><span>{enabledLabel(item.before_enabled)} → {enabledLabel(item.after_enabled)}</span><small>{labels[item.state]||item.state}</small></button>)}</details>
 </>}</section>
}
