import React,{useEffect,useRef,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {Plus,Trash2,Check,ChevronDown,LoaderCircle,X,Search,Download} from 'lucide-react';
import './model-settings.css';
const budgets=[['max_output_tokens','最大输出 token'],['timeout','超时（秒）'],['max_tool_calls','最多工具调用'],['max_requests','最多模型请求']];
function draftOf(p){return {id:p?.id,name:p?.name||'',config:{endpoint:'',model:'',...p?.config},models:(p?.models||[]).map(m=>({...m})),api_key:'',clear_key:false}}
export default function ModelSettings({post,offline=false}){
 const [data,setData]=useState(null),[edit,setEdit]=useState(null),[base,setBase]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState(null),[picker,setPicker]=useState(null),[search,setSearch]=useState(''),[selected,setSelected]=useState([]),[tested,setTested]=useState([]);
 const alive=useRef(true),lock=useRef(false),postRef=useRef(post);postRef.current=post;
 const dirty=!!edit&&JSON.stringify(edit)!==base,disabled=offline||!!busy;
 async function run(kind,work){if(lock.current||offline)return;lock.current=true;setBusy(kind);setError('');setNotice('');try{await work()}catch(e){if(alive.current)setError(e.message||'请求失败，请重试。')}finally{lock.current=false;if(alive.current)setBusy('')}}
 async function api(action,body={}){return postRef.current('model/catalog',{action,...body})}
 function accept(value){if(alive.current)setData(value)}
 function load(){return run('load',async()=>accept(await api('list')))}
 useEffect(()=>{alive.current=true;load();return()=>{alive.current=false}},[]);
 useEffect(()=>{if(!offline&&!data&&!lock.current)load()},[offline]);
 function open(p){const next=draftOf(p);setEdit(next);setBase(JSON.stringify(next));setNotice('');setError('')}
 function leave(next){if(dirty)setConfirm({kind:'discard',next});else next()}
 function patch(values){setEdit(e=>({...e,...values}));setNotice('')}
 function config(field,value){setEdit(e=>({...e,config:{...e.config,[field]:value}}));setNotice('')}
 function modelChange(index,field,value){setEdit(e=>{const models=e.models.map((m,i)=>i===index?{...m,[field]:value}:m);return {...e,models,config:{...e.config,model:field==='id'&&e.config.model===e.models[index].id?value:e.config.model}}})}
 function removeModel(index){setEdit(e=>({...e,models:e.models.filter((_,i)=>i!==index),config:{...e.config,model:e.config.model===e.models[index].id?'':e.config.model}}))}
 function save(event){event.preventDefault();run('save',async()=>{const config={...edit.config,endpoint:edit.config.endpoint.trim(),model:edit.config.model.trim()};for(const [field]of budgets){if(config[field]===''||config[field]==null){delete config[field];continue}const value=Number(config[field]);if(!Number.isInteger(value)||value<(field==='max_tool_calls'?0:1))throw Error('工具调用次数可为零；其他预算与超时请填写大于零的整数。');config[field]=value}const models=edit.models.map(m=>({id:m.id.trim(),name:m.name.trim()||m.id.trim()}));if(models.some(m=>!m.id))throw Error('请填写每个模型的标识，或移除空白行。');if(new Set(models.map(m=>m.id)).size!==models.length)throw Error('模型标识不能重复。');const body={id:edit.id,name:edit.name.trim(),config,models};if(edit.clear_key)body.clear_key=true;else if(edit.api_key)body.api_key=edit.api_key;accept(await api('save',body));setTested(t=>t.filter(id=>id!==edit.id));setEdit(null);setNotice('提供商已保存。')})}
 function fetchModels(){run('models',async()=>{const value=await api('models',{id:edit.id});setPicker(value.models||[]);setSearch('');setSelected([])})}
 function test(id){run('test',async()=>{setTested(t=>t.filter(v=>v!==id));const result=await api('test',{id});if(!result.ok)throw Error(result.message||'本次测试未通过。');setTested(t=>[...t.filter(v=>v!==id),id]);setNotice('本次测试通过；测试仅发送通用连通性问题。')})}
 function activate(p){leave(()=>run('activate',async()=>{accept(await api('activate',{id:p.id,model:p.config.model}));setEdit(null);setNotice('已切换当前使用的提供商。')}))}
 const saved=edit?.id&&data?.providers.find(p=>p.id===edit.id),visible=(picker||[]).filter(m=>(m.id+' '+m.name).toLowerCase().includes(search.toLowerCase())),available=visible.filter(m=>!edit?.models.some(e=>e.id===m.id));
 function editor(){return <form className="provider-editor" onSubmit={save}>
 <label>提供商名称<input autoComplete="off" value={edit.name} onChange={e=>patch({name:e.target.value})} disabled={disabled} placeholder="便于识别的名称"/></label>
 <label>接口地址<input type="url" autoComplete="off" value={edit.config.endpoint} onChange={e=>config('endpoint',e.target.value)} disabled={disabled} placeholder="OpenAI 兼容基础地址" spellCheck={false}/></label>
 <label>API 密钥<input type="password" autoComplete="new-password" value={edit.api_key} onChange={e=>patch({api_key:e.target.value,clear_key:false})} disabled={disabled||edit.clear_key} placeholder={saved?.key_configured?'留空保留已存密钥':'输入 API 密钥'} /></label>
 <p className="provider-hint">密钥不会回显或保存在浏览器缓存中。{saved?.key_configured?'当前已保存密钥。':'当前未保存密钥。'}</p>
 {saved?.key_configured&&<label className="provider-check"><input type="checkbox" checked={edit.clear_key} disabled={disabled} onChange={e=>patch({clear_key:e.target.checked,api_key:''})}/>保存时移除已存密钥</label>}
 <div className="provider-model-heading"><h3>模型目录</h3><button type="button" className="text-button" disabled={disabled||!edit.id||dirty} onClick={fetchModels}><Download size={14}/>获取可用模型</button></div>
 <p className="provider-hint">填写服务提供的模型标识，再选择默认模型。获取目录与测试使用已保存的设置。</p>
 {!edit.models.length&&<p className="provider-empty">尚未添加模型。可手工添加，或保存提供商后获取目录。</p>}
 <div className="provider-models">{edit.models.map((m,i)=><div className="provider-model" key={i}><label className="provider-default"><input type="radio" name="default-model" aria-label={'默认模型 '+(m.id||i+1)} disabled={disabled||!m.id} checked={!!m.id&&edit.config.model===m.id} onChange={()=>config('model',m.id)}/><span>默认</span></label><label>模型标识<input aria-label={'模型标识 '+(i+1)} value={m.id} disabled={disabled} onChange={e=>modelChange(i,'id',e.target.value)} placeholder="模型 ID"/></label><label>显示名称<input aria-label={'显示名称 '+(i+1)} value={m.name} disabled={disabled} onChange={e=>modelChange(i,'name',e.target.value)} placeholder="可选，便于识别"/></label><button type="button" className="icon-button" aria-label={'移除模型 '+(m.id||i+1)} disabled={disabled} onClick={()=>removeModel(i)}><Trash2 size={15}/></button></div>)}</div>
 <button type="button" className="text-button" disabled={disabled} onClick={()=>patch({models:[...edit.models,{id:'',name:''}]})}><Plus size={14}/>手工添加模型</button>
 <details className="provider-budgets"><summary>调用预算与超时</summary><p className="provider-hint">每次任务的上限，最后一轮用于整理结果。</p><button type="button" className="text-button" disabled={disabled||!data?.budget_defaults} onClick={()=>patch({config:{...edit.config,...data.budget_defaults}})}>使用推荐额度</button><div className="model-budget-grid">{budgets.map(([field,label])=><label key={field}>{label}<input type="number" min={data?.budget_limits?.[field]?.[0]??(field==='max_tool_calls'?0:1)} max={data?.budget_limits?.[field]?.[1]} step="1" value={edit.config[field]??''} disabled={disabled} onChange={e=>config(field,e.target.value)} placeholder={String(data?.budget_defaults?.[field]??'')}/></label>)}</div></details>
 <div className="provider-editor-footer"><span>{dirty?'有未保存的修改':'设置已保存'}</span><button type="button" className="button" disabled={disabled} onClick={()=>leave(()=>setEdit(null))}>取消</button><button className="button primary" disabled={disabled||(!dirty&&!!edit.id)}>{busy==='save'?<LoaderCircle size={14} className="spin"/>:<Check size={14}/>}保存提供商</button></div></form>}
 return <section className="settings-section model-settings" aria-labelledby="model-settings-title"><h2 id="model-settings-title">模型提供商</h2><p className="model-settings-intro">管理 OpenAI 兼容连接与模型目录。真实分析会发送请求、会话上下文及授权范围内的脱敏清单摘要，可能按需读取目录名称。</p>
 {offline&&<p className="model-settings-feedback" role="status">本地服务离线，连接恢复后可继续设置。</p>}
 {error&&<div className="model-settings-feedback" role="alert">{error}{!data&&<button className="text-button" disabled={disabled} onClick={load}>重试加载</button>}</div>}
 {notice&&<p className="model-settings-feedback" role="status">{notice}</p>}
 {!data?<p className="provider-empty">{busy?'正在读取提供商…':'提供商尚未加载。'}</p>:<><div className="provider-list">{data.providers.map(p=><article className="provider-item" key={p.id}><div className="provider-row"><div className="provider-identity"><div><strong>{p.name}</strong>{p.id===data.active_id&&<span className="provider-active">当前使用</span>}</div><p>{tested.includes(p.id)?'本次测试通过':p.config.endpoint&&p.config.model?'已配置':'未配置'}{p.config.model&&<> · {p.models.find(m=>m.id===p.config.model)?.name||p.config.model}</>}</p></div><div className="provider-controls">{p.id!==data.active_id&&<button className="text-button" disabled={disabled||!p.config.endpoint||!p.config.model} onClick={()=>activate(p)}>使用</button>}<button className="button" aria-expanded={edit?.id===p.id} disabled={disabled} onClick={()=>leave(()=>edit?.id===p.id?setEdit(null):open(p))}>编辑<ChevronDown size={14}/></button>{p.id!==data.active_id&&<button className="icon-button" aria-label={'删除提供商 '+p.name} disabled={disabled} onClick={()=>leave(()=>setConfirm({kind:'delete',provider:p}))}><Trash2 size={15}/></button>}</div></div>{edit?.id===p.id&&<>{editor()}<button className="text-button provider-test" disabled={disabled||dirty||!p.config.endpoint||!p.config.model} onClick={()=>test(p.id)}>测试连接</button></>}</article>)}</div>
 {edit&&!edit.id?<div className="provider-new"><h3>添加提供商</h3>{editor()}</div>:<button className="button provider-add" disabled={disabled} onClick={()=>leave(()=>open(null))}><Plus size={16}/>添加模型提供商</button>}
 {!data.providers.length&&!edit&&<p className="provider-empty">添加一个提供商，开始配置真实只读助手。</p>}</>}
 <Dialog.Root open={!!confirm} onOpenChange={v=>{if(!v&&!busy)setConfirm(null)}}><Dialog.Portal><Dialog.Overlay className="model-dialog-overlay"/><Dialog.Content className="model-dialog model-confirm"><Dialog.Title>{confirm?.kind==='delete'?'删除提供商？':'放弃未保存的修改？'}</Dialog.Title><Dialog.Description>{confirm?.kind==='delete'?`将删除“${confirm.provider.name}”的本地连接与密钥登记。`:'返回编辑可保留当前输入；放弃后不会保存这些修改。'}</Dialog.Description><div className="model-dialog-footer"><button className="button" disabled={disabled} onClick={()=>setConfirm(null)}>{confirm?.kind==='delete'?'取消':'返回编辑'}</button><button className="button primary" disabled={disabled} onClick={()=>{const action=confirm;if(action.kind==='discard'){setConfirm(null);setEdit(null);action.next()}else run('delete',async()=>{accept(await api('delete',{id:action.provider.id}));setEdit(null);setConfirm(null);setNotice('提供商已删除。')})}}>{confirm?.kind==='delete'?'确认删除':'放弃修改'}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
 <Dialog.Root open={picker!==null} onOpenChange={v=>{if(!v)setPicker(null)}}><Dialog.Portal><Dialog.Overlay className="model-dialog-overlay"/><Dialog.Content className="model-dialog"><Dialog.Title>选择要添加的模型</Dialog.Title><Dialog.Description>从已保存提供商获取的目录中选择。添加后仍需保存提供商。</Dialog.Description><Dialog.Close className="icon-button model-dialog-close" aria-label="关闭模型目录"><X size={18}/></Dialog.Close><label className="model-search"><Search size={16}/><input aria-label="搜索模型" placeholder="搜索模型名称或 ID" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="provider-check model-select-all"><input type="checkbox" checked={available.length>0&&available.every(m=>selected.includes(m.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...available.map(m=>m.id)])]:selected.filter(id=>!available.some(m=>m.id===id)))}/>选择当前搜索结果</label><div className="model-picker-list">{visible.map(m=>{const existing=edit?.models.some(e=>e.id===m.id);return <label key={m.id}><input type="checkbox" disabled={existing} checked={existing||selected.includes(m.id)} onChange={e=>setSelected(e.target.checked?[...selected,m.id]:selected.filter(id=>id!==m.id))}/><span><strong>{m.name||m.id}</strong><small>{m.id}</small></span>{existing&&<em>已添加</em>}</label>})}{!visible.length&&<p className="provider-empty">没有匹配的模型。</p>}</div><div className="model-dialog-footer"><button className="button" onClick={()=>setPicker(null)}>取消</button><button className="button primary" disabled={!selected.length||offline} onClick={()=>{patch({models:[...edit.models,...picker.filter(m=>selected.includes(m.id)&&!edit.models.some(e=>e.id===m.id))]});setPicker(null)}}>添加所选{selected.length?`（${selected.length}）`:''}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
 </section>
}
