import React,{useEffect,useRef,useState} from 'react';
import {Plus,Trash2,LoaderCircle,RefreshCw} from 'lucide-react';
import './source-settings.css';

const labels={portable:'便携软件',project:'项目配置'};
export default function SourceSettings({post,offline=false,onChanged,onScan}){
 const [sources,setSources]=useState([]),[type,setType]=useState('portable'),[path,setPath]=useState(''),[label,setLabel]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[removing,setRemoving]=useState(null);
 const alive=useRef(true),lock=useRef(false),postRef=useRef(post);
 postRef.current=post;
 const disabled=!!busy||offline||!loaded;
 async function list(){const result=await postRef.current('source/list',{});if(alive.current){setSources(result.sources||[]);setLoaded(true)}}
 async function operate(kind,work){if(lock.current||offline)return;lock.current=true;setBusy(kind);setError('');setNotice('');try{await work()}catch(e){if(alive.current)setError(e.message||'请求未完成，请重试。')}finally{lock.current=false;if(alive.current)setBusy('')}}
 useEffect(()=>{alive.current=true;operate('load',list);return()=>{alive.current=false}},[]);
 useEffect(()=>{if(!offline&&!loaded&&!lock.current)operate('load',list)},[offline]);
 function add(event){event.preventDefault();if(disabled)return;operate('add',async()=>{const absolute=path.trim();if(!/^(?:[a-zA-Z]:[\\/]|\\\\[^\\/]+[\\/][^\\/]+)/.test(absolute))throw Error('请输入完整的绝对目录路径，例如盘符路径或网络共享路径。');await postRef.current('source/add',{type,path:absolute,label:label.trim()});if(!alive.current)return;setPath('');setLabel('');await list();if(!alive.current)return;setNotice('来源登记已保存，重新检查后生效。');await onChanged?.()})}
 function remove(id){operate('remove',async()=>{await postRef.current('source/remove',{id});if(!alive.current)return;setRemoving(null);await list();if(!alive.current)return;setNotice('已移除来源登记，目录和文件保持不变。重新检查后更新清单。');await onChanged?.()})}
 return <section className="settings-section source-settings" aria-labelledby="source-settings-title"><div className="source-settings-heading"><div><h2 id="source-settings-title">补充检查来源</h2><p>登记需要纳入检查的目录。登记变更会在下一次检查时生效。</p></div>{onScan&&<button type="button" className="button" disabled={disabled} onClick={()=>operate('scan',async()=>{await onScan()})}><RefreshCw size={14} className={busy==='scan'?'spin':''}/>重新检查</button>}</div>
 {offline&&<p className="source-settings-feedback" role="status">本地服务离线，暂不可新增或移除来源登记。</p>}{error&&<div className="source-settings-feedback" role="alert"><span>{error}</span>{!loaded&&<button type="button" className="text-button" disabled={!!busy||offline} onClick={()=>operate('load',list)}>重试加载</button>}</div>}{notice&&<p className="source-settings-feedback" role="status">{notice}</p>}
 <form onSubmit={add}><div className="source-type-options" role="group" aria-label="来源类型">{Object.entries(labels).map(([value,name])=><button type="button" key={value} aria-pressed={type===value} disabled={disabled} onClick={()=>{setType(value);setNotice('')}}>{name}</button>)}</div><p className="source-scope">{type==='portable'?'便携软件：只检查所选根目录及下一级目录中的 EXE 入口元数据，不运行程序。':'项目配置：只检查项目中的 .codex/config.toml 和 .mcp.json，不执行其中的命令或其他内容。'}</p><div className="setting-row source-settings-field"><div><label htmlFor="source-path">绝对目录路径</label><p>{type==='portable'?'填写便携软件的存放目录。':'填写项目根目录。'}</p></div><input id="source-path" value={path} disabled={disabled} onChange={e=>setPath(e.target.value)} autoComplete="off" placeholder="例如 C:\Tools 或 D:\Projects\MyProject" spellCheck={false} required/></div><div className="setting-row source-settings-field"><div><label htmlFor="source-label">显示名称（可选）</label><p>便于在登记列表中识别。</p></div><input id="source-label" value={label} disabled={disabled} onChange={e=>setLabel(e.target.value)} maxLength={120} autoComplete="off" placeholder="例如 我的便携工具"/></div><button type="submit" className="button primary" disabled={disabled||!path.trim()}>{busy==='add'?<LoaderCircle size={15} className="spin"/>:<Plus size={15}/>}登记来源</button></form>
 <div className="source-list-heading"><h3>已登记来源</h3><span>{sources.length} 项</span></div>{!loaded?<p className="source-scope">{busy==='load'?'正在读取来源登记…':'来源登记尚未加载。'}</p>:!sources.length?<p className="source-scope">还没有补充来源。登记只影响工作台的检查范围。</p>:<ul className="source-list">{sources.map(source=><li key={source.id}><div className="source-list-row"><div><strong>{source.label||labels[source.type]||'登记目录'}</strong><span>{labels[source.type]||source.type}</span><code>{source.path}</code></div><button type="button" className="text-button" disabled={disabled} aria-label={'移除登记 '+(source.label||source.path)} onClick={()=>setRemoving(source.id)}><Trash2 size={14}/>移除登记</button></div>{removing===source.id&&<div className="source-remove-confirm"><p>只移除此来源的登记，不删除目录或文件。</p><button type="button" className="button" disabled={disabled} onClick={()=>remove(source.id)}>确认移除登记</button><button type="button" className="text-button" disabled={!!busy} onClick={()=>setRemoving(null)}>取消</button></div>}</li>)}</ul>}
 </section>
}
