import React,{useEffect,useRef,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {Palette,Check,ChevronLeft,ChevronRight,Sun,Moon,Monitor} from 'lucide-react';
import {themes} from './themes';
import './theme-wheel.css';
export function AppearanceMode({value,onChange}){return <div className="appearance-modes" role="group" aria-label="明暗模式">{[['light','浅色',Sun],['dark','深色',Moon],['system','系统',Monitor]].map(([id,label,Icon])=><button key={id} type="button" aria-label={id==='system'?'跟随系统':label} title={id==='system'?'跟随系统':label} aria-pressed={value===id} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();onChange({mode:id},{x:r.left+r.width/2,y:r.top+r.height/2})}}><Icon size={14}/></button>)}</div>}
const step=30;
const wrap=n=>((n%themes.length)+themes.length)%themes.length;
export default function ThemeWheel({value,onChange,settings=false}){
 const [open,setOpen]=useState(false),[rotation,setRotation]=useState(-45),[position,setPosition]=useState({left:12,top:12,size:390});const wheel=useRef(null),trigger=useRef(null),drag=useRef(null),suppress=useRef(false),delta=useRef(0),modality=useRef('pointer');
 const previewMode=value.mode==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value.mode;
 const active=themes.find(t=>t.id===value.palette)||themes[0],index=wrap(Math.round((-45-rotation)/step)),browsed=themes[index];
 function origin(){const r=trigger.current?.querySelector('svg')?.getBoundingClientRect();return r?{x:r.left+r.width/2,y:r.top+r.height/2}:undefined}
 useEffect(()=>{if(open&&browsed.id!==value.palette)onChange({palette:browsed.id},origin())},[open,index]);
 const browse=n=>setRotation(r=>r-n*step);
 function locate(){const icon=trigger.current?.querySelector('svg'),rect=(icon||trigger.current)?.getBoundingClientRect();if(!rect)return;const size=Math.min(390,window.innerWidth-24,window.innerHeight-24),left=Math.max(12,Math.min(rect.left+rect.width/2,window.innerWidth-size-12)),bottom=Math.max(size+12,Math.min(rect.top-8,window.innerHeight-12));setPosition({left,top:bottom-size,size})}
 useEffect(()=>{const pointer=()=>{modality.current='pointer'},keyboard=()=>{modality.current='keyboard';trigger.current?.removeAttribute('data-theme-focus-return')};window.addEventListener('pointerdown',pointer,true);window.addEventListener('keydown',keyboard,true);return()=>{window.removeEventListener('pointerdown',pointer,true);window.removeEventListener('keydown',keyboard,true)}},[]);
 useEffect(()=>{if(!open)return;delta.current=0;function scroll(e){e.preventDefault();e.stopPropagation();const node=wheel.current,rect=node?.getBoundingClientRect();if(!rect||!node.contains(e.target)||e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)return;e.preventDefault();e.stopPropagation();delta.current+=(e.deltaY||e.deltaX)*(e.deltaMode===1?16:e.deltaMode===2?rect.height:1);if(Math.abs(delta.current)>=35){browse(Math.sign(delta.current));delta.current=0}}const blockTouch=e=>e.preventDefault();const blockKeys=e=>{if(['PageDown','PageUp','Home','End','ArrowDown','ArrowUp',' '].includes(e.key)&&!wheel.current?.contains(e.target))e.preventDefault()};window.addEventListener('touchmove',blockTouch,{capture:true,passive:false});window.addEventListener('keydown',blockKeys,true);window.addEventListener('wheel',scroll,{capture:true,passive:false});window.addEventListener('resize',locate);window.addEventListener('scroll',locate,true);return()=>{window.removeEventListener('touchmove',blockTouch,true);window.removeEventListener('keydown',blockKeys,true);window.removeEventListener('wheel',scroll,true);window.removeEventListener('resize',locate);window.removeEventListener('scroll',locate,true)}},[open]);
 function show(next){if(next){locate();setRotation(-45-Math.max(0,themes.findIndex(t=>t.id===value.palette))*step);}setOpen(next)}
 function angleAt(e){const rect=wheel.current.getBoundingClientRect();return Math.atan2(e.clientY-rect.bottom,e.clientX-rect.left)*180/Math.PI}
 function down(e){if(e.button!==0||e.target.closest('.theme-wheel-controls'))return;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,last:angleAt(e),moved:false};suppress.current=false}
 function move(e){const d=drag.current;if(!d||d.id!==e.pointerId)return;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>6){if(!d.moved)e.currentTarget.setPointerCapture(e.pointerId);d.moved=true;suppress.current=true;const angle=angleAt(e),change=((angle-d.last+540)%360)-180;setRotation(r=>r+change);d.last=angle;e.preventDefault()}}
 function release(){if(drag.current?.moved)setRotation(r=>-45-Math.round((-45-r)/step)*step);drag.current=null;setTimeout(()=>{suppress.current=false},0)}
 function apply(id){if(!suppress.current)setRotation(-45-themes.findIndex(theme=>theme.id===id)*step)}
 function keys(e){if(e.target!==wheel.current)return;if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();if(e.key==='Home')setRotation(-45);else if(e.key==='End')setRotation(-45-(themes.length-1)*step);else browse(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)}else if(e.key==='Enter'||e.key===' '){e.preventDefault();apply(browsed.id)}}
 return <Dialog.Root modal={false} open={open} onOpenChange={show}><Dialog.Trigger asChild><button ref={trigger} type="button" className={settings?'button appearance-settings-trigger':'appearance-trigger'} aria-label="选择主题"><Palette size={17}/><span>{settings?'选择主题':active.name}</span><ChevronRight size={14}/></button></Dialog.Trigger><Dialog.Portal>{open&&<div className="theme-wheel-backdrop" aria-hidden="true" onPointerDown={()=>show(false)}/>}<Dialog.Content ref={wheel} className="theme-wheel-panel" style={{left:position.left,top:position.top,bottom:'auto',width:position.size,height:position.size}} inert={!open} tabIndex={-1} onCloseAutoFocus={e=>{e.preventDefault();if(modality.current==='pointer')trigger.current?.setAttribute('data-theme-focus-return','pointer');else trigger.current?.removeAttribute('data-theme-focus-return');trigger.current?.focus({preventScroll:true})}} onOpenAutoFocus={e=>{e.preventDefault();wheel.current?.focus()}} onKeyDown={keys} onPointerDown={down} onPointerMove={move} onPointerUp={release} onPointerCancel={release} onClickCapture={e=>{if(suppress.current){e.preventDefault();e.stopPropagation()}}}><Dialog.Title className="theme-wheel-title">外观主题</Dialog.Title><Dialog.Description className="theme-wheel-help">拖动、滚轮或方向键切换，中间的主题立即应用。</Dialog.Description><svg className="theme-quarter-track" viewBox="0 0 390 390" aria-hidden="true"><path d="M 0 74 A 316 316 0 0 1 316 390"/><path d="M 0 123 A 267 267 0 0 1 267 390"/></svg>
 {themes.map((theme,i)=>{const angle=((i*step+rotation+90)%180+180)%180-90,visible=angle>=-86&&angle<=-4,r=angle*Math.PI/180;return <button key={theme.id} hidden={!visible} className={'theme-wheel-swatch '+(i===index?'is-browsed':'')} style={{left:`${Math.cos(r)*81}%`,top:`${100+Math.sin(r)*81}%`,'--chip-bg':theme[previewMode].bg,'--chip-accent':theme[previewMode].accent}} type="button" aria-label={'应用'+theme.name} aria-pressed={value.palette===theme.id} onClick={()=>apply(theme.id)}><span>{value.palette===theme.id&&<Check size={16}/>}</span><small>{theme.name}</small></button>})}
 <div className="theme-wheel-controls"><div className="theme-quarter-browse"><button className="icon-button" aria-label="浏览上一主题" onClick={()=>browse(-1)}><ChevronLeft size={15}/></button><span>{index+1} / {themes.length}</span><button className="icon-button" aria-label="浏览下一主题" onClick={()=>browse(1)}><ChevronRight size={15}/></button></div><strong className="theme-browsed-name" aria-live="polite">{browsed.name}</strong><p className="theme-browsed-note">{browsed.note}</p><AppearanceMode value={value.mode} onChange={next=>onChange(next,origin())}/><p className="theme-wheel-status" role="status">{value.failed?'已应用，本次未能保存偏好。':`已应用 · ${active.name}`}</p></div>
 </Dialog.Content></Dialog.Portal></Dialog.Root>
}
