import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
export const themes=window.DeskThemes.themes;
export function useAppearance(){
 const [value,setValue]=useState(()=>({...window.DeskThemes.read(),failed:false})),latest=useRef(value),serial=useRef(0),transition=useRef(null),motion=useRef(null);
 function immediate(next,persist){serial.current++;motion.current?.cancel();motion.current=null;transition.current?.skipTransition();document.documentElement.removeAttribute('data-theme-transition');const applied=window.DeskThemes.apply(next,persist);latest.current=applied;setValue(applied)}
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)'),system=()=>{if(latest.current.mode==='system')immediate(latest.current,false)};media.addEventListener('change',system);const storage=e=>{if(['desk-appearance','desk-theme',null].includes(e.key))immediate(window.DeskThemes.read(),false)};window.addEventListener('storage',storage);return()=>{serial.current++;motion.current?.cancel();motion.current=null;transition.current?.skipTransition();document.documentElement.removeAttribute('data-theme-transition');media.removeEventListener('change',system);window.removeEventListener('storage',storage)}},[]);
 function change(next,origin){const desired=window.DeskThemes.validate({...latest.current,...next});if(desired.palette===latest.current.palette&&desired.mode===latest.current.mode)return;latest.current=desired;const ticket=++serial.current;motion.current?.cancel();motion.current=null;transition.current?.skipTransition();const commit=(sync=false)=>{if(ticket!==serial.current)return;const applied=window.DeskThemes.apply(desired,true);latest.current=applied;sync?flushSync(()=>setValue(applied)):setValue(applied)};if(!document.startViewTransition||matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.removeAttribute('data-theme-transition');commit();return}
 const icon=document.querySelector('.appearance-trigger svg'),rect=icon?.getBoundingClientRect(),x=Math.max(0,Math.min(innerWidth,origin?.x??(rect?rect.left+rect.width/2:24))),y=Math.max(0,Math.min(innerHeight,origin?.y??(rect?rect.top+rect.height/2:innerHeight-24))),radius=Math.hypot(Math.max(x,innerWidth-x),Math.max(y,innerHeight-y));document.documentElement.setAttribute('data-theme-transition','ink');let current;try{current=document.startViewTransition(()=>commit(true));transition.current=current}catch{document.documentElement.removeAttribute('data-theme-transition');commit();return}current.ready.then(()=>{if(ticket!==serial.current)return;motion.current=document.documentElement.animate({clipPath:[`circle(0px at ${x}px ${y}px)`,`circle(${radius}px at ${x}px ${y}px)`]},{duration:460,easing:'cubic-bezier(.18,.7,.25,1)',fill:'both',pseudoElement:'::view-transition-new(root)'});return motion.current.finished}).catch(()=>{});current.finished.finally(()=>{if(ticket===serial.current){motion.current?.cancel();motion.current=null;document.documentElement.removeAttribute('data-theme-transition');transition.current=null}}).catch(()=>{});
 }
 return [value,change];
}
