import React,{useEffect,useRef,useState} from 'react';
import {Plus,Trash2,RefreshCw,Check,ArrowRight} from 'lucide-react';
import './agent-settings.css';

const empty=()=>({name:'',transport:'stdio',url:'',token:'',clear_token:false,command:'',args:[],cwd:'',enabled:false,allowed_tools:[]});
export default function AgentSettings({post,offline,onOpen}){
 const [servers,setServers]=useState([]),[draft,setDraft]=useState(null),[args,setArgs]=useState(''),[instructions,setInstructions]=useState(''),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[remove,setRemove]=useState(null),[ack,setAck]=useState(false);
 const ref=useRef(post),alive=useRef(true),lock=useRef(false);ref.current=post;
 async function load(){const [a,b]=await Promise.all([ref.current('agent/preferences',{}),ref.current('mcp-client/list',{})]);if(!alive.current)return;setInstructions(a.preferences.instructions);setSaved(a.preferences.instructions);setServers(b.servers||[]);setLoaded(true)}
 async function loadServers(){const result=await ref.current('mcp-client/list',{});if(alive.current)setServers(result.servers||[])}
 async function act(work){if(lock.current||offline)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await work()}catch(e){if(alive.current)setError(e.message||'请求未完成')}finally{lock.current=false;if(alive.current)setBusy(false)}}
 useEffect(()=>{alive.current=true;act(load);return()=>{alive.current=false}},[]);
 useEffect(()=>{if(!offline&&!loaded&&!lock.current)act(load)},[offline]);
 function edit(item){setDraft({transport:'stdio',token:'',clear_token:false,...item});setArgs((item.args||[]).join('\n'));setAck(false);setError('');setNotice('')}
 async function save(){await act(async()=>{const payload={...(draft.id?{id:draft.id}:{}),name:draft.name,transport:draft.transport,...(draft.transport==='streamable-http'?{url:draft.url,token:draft.token,clear_token:draft.clear_token}:{}),command:draft.command,cwd:draft.cwd,enabled:draft.enabled,allowed_tools:draft.allowed_tools,args:args.split('\n').filter(s=>s.trim()),acknowledge_execution:ack};await ref.current('mcp-client/save',payload);setDraft(null);await loadServers();setNotice('连接设置已保存。')})}
 async function discover(){await act(async()=>{const result=await ref.current('mcp-client/discover',{id:draft.id,acknowledge_execution:ack});const list=await ref.current('mcp-client/list',{});setServers(list.servers||[]);const updated=(list.servers||[]).find(s=>s.id===draft.id);setDraft({...draft,...updated,tools:result.tools||updated?.tools||[]});setNotice('已读取工具目录，勾选允许助手调用的工具后保存。')})}
 const disabled=busy||offline||!loaded;
 const stored=servers.find(s=>s.id===draft?.id),connectionChanged=!!stored&&(draft.transport!==(stored.transport||'stdio')||draft.url!==stored.url||!!draft.token||draft.clear_token||draft.command!==stored.command||draft.cwd!==stored.cwd||JSON.stringify(args.split('\n').filter(s=>s.trim()))!==JSON.stringify(stored.args||[]));
 return <section className="settings-section agent-settings"><div className="agent-settings-heading"><div><h2>归处助手</h2><p>管理回答偏好和助手可以调用的外部工具。</p></div><button className="button" onClick={onOpen}>打开助手<ArrowRight size={14}/></button></div>
 {offline&&<p role="status">本地服务离线，连接设置暂不可修改。</p>}{error&&<div role="alert" className="agent-settings-feedback">{error}{!loaded&&<button className="text-button" disabled={busy||offline} onClick={()=>act(load)}>重新加载</button>}</div>}{notice&&<p role="status" className="agent-settings-feedback">{notice}</p>}
 <label className="agent-preferences">使用偏好<textarea value={instructions} disabled={disabled} maxLength={2000} placeholder="例如：回答简洁；介绍工具时优先说明用途和关联。" onChange={e=>setInstructions(e.target.value)}/></label><div className="agent-settings-footer"><span>{instructions.length}/2000 · 下次请求生效</span><button className="button" disabled={disabled||instructions===saved} onClick={()=>act(async()=>{const r=await ref.current('agent/preferences',{instructions});setInstructions(r.preferences.instructions);setSaved(r.preferences.instructions);setNotice('使用偏好已保存。')})}><Check size={14}/>保存偏好</button></div>
 <div className="agent-settings-heading mcp-connections-heading"><div><h3>助手的 MCP 连接</h3><p>连接本机 stdio 或远程 Streamable HTTP 服务，选择允许调用的只读工具。</p></div><button className="button" disabled={disabled||!!draft} onClick={()=>edit(empty())}><Plus size={14}/>添加连接</button></div>
 {!loaded?<p className="muted">{busy?'正在读取设置…':'设置尚未加载。'}</p>:!servers.length&&!draft?<p className="muted">还没有连接。归处的本机查询与修改预览工具可直接使用。</p>:null}
 <div className="agent-connections">{servers.filter(s=>s.id!==draft?.id).map(s=><div className="agent-connection" key={s.id}><div><strong>{s.name}</strong><small>{s.enabled?'已允许助手调用':'未启用'} · {(s.allowed_tools||[]).length} 个工具</small></div><button className="text-button" disabled={disabled||!!draft} onClick={()=>edit(s)}>编辑</button><button className="icon-button" aria-label={'移除连接 '+s.name} disabled={disabled} onClick={()=>setRemove(s.id)}><Trash2 size={14}/></button>{remove===s.id&&<div className="agent-remove"><span>移除此连接登记？</span><button className="text-button" disabled={disabled} onClick={()=>act(async()=>{await ref.current('mcp-client/delete',{id:s.id});setRemove(null);await loadServers()})}>确认移除</button><button className="text-button" onClick={()=>setRemove(null)}>取消</button></div>}</div>)}</div>
 {draft&&<form className="agent-connection-editor" onSubmit={e=>{e.preventDefault();save()}}><label>连接名称<input required value={draft.name} disabled={disabled} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>连接方式<select aria-label="连接方式" value={draft.transport} disabled={disabled} onChange={e=>{setAck(false);setDraft({...empty(),id:draft.id,name:draft.name,transport:e.target.value});setArgs('')}}><option value="stdio">本机程序 · stdio</option><option value="streamable-http">远程服务 · Streamable HTTP</option></select></label>{draft.transport==='streamable-http'?<><label>服务地址<input required type="url" value={draft.url||''} disabled={disabled} placeholder="https://example.com/mcp" onChange={e=>{setAck(false);setDraft({...draft,url:e.target.value,enabled:false,allowed_tools:[],tools:[]})}}/></label><label>访问令牌 <small>可选，使用 Bearer 认证</small><input type="password" autoComplete="new-password" value={draft.token||''} disabled={disabled} placeholder={draft.has_token?'已保存；留空保留，输入新值替换':'输入服务提供的令牌'} onChange={e=>{setAck(false);setDraft({...draft,token:e.target.value,enabled:false,allowed_tools:[],tools:[]})}}/></label>{draft.has_token&&<label className="agent-check"><input type="checkbox" checked={!!draft.clear_token} disabled={disabled} onChange={e=>{setAck(false);setDraft({...draft,clear_token:e.target.checked,enabled:false,allowed_tools:[],tools:[]})}}/>移除已保存令牌</label>}<p className="muted">令牌在本机加密保存，不会返回页面。修改服务地址后需重新填写令牌并审核工具。</p></>:<><label>可执行程序<input required value={draft.command} disabled={disabled} placeholder="程序的本机绝对路径" onChange={e=>{setAck(false);setDraft({...draft,command:e.target.value,enabled:false,allowed_tools:[],tools:[]})}}/></label><label>启动参数 <small>每行一个参数</small><textarea value={args} disabled={disabled} onChange={e=>{setAck(false);setArgs(e.target.value);setDraft({...draft,enabled:false,allowed_tools:[],tools:[]})}} spellCheck={false}/></label><label>工作目录<input required value={draft.cwd} disabled={disabled} placeholder="本机绝对目录路径" onChange={e=>{setAck(false);setDraft({...draft,cwd:e.target.value,enabled:false,allowed_tools:[],tools:[]})}}/></label></>}
 <label className="agent-check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} disabled={disabled}/>{draft.transport==='streamable-http'?'我信任此服务，允许连接并向其发送所选工具的调用参数。':'我信任此程序，允许归处启动它以发现和调用工具。'}</label>
 {draft.id&&<button className="button" type="button" disabled={disabled||!ack||connectionChanged} onClick={discover}><RefreshCw size={14}/>读取已保存连接的工具</button>}
 {connectionChanged&&<p className="muted">连接设置已修改，请先保存，再读取工具目录。</p>}{!!draft.tools?.length&&<fieldset><legend>允许调用的工具</legend>{draft.tools.map(tool=>{const safe=tool.readOnlyHint===true||tool.annotations?.readOnlyHint===true;return <label className="agent-tool" key={tool.name}><input type="checkbox" disabled={disabled||!safe} checked={draft.allowed_tools.includes(tool.name)} onChange={e=>{const allowed=e.target.checked?[...draft.allowed_tools,tool.name]:draft.allowed_tools.filter(n=>n!==tool.name);setDraft({...draft,allowed_tools:allowed,enabled:allowed.length?draft.enabled:false})}}/><span><strong>{tool.name}</strong><small>{tool.description||'无工具说明'}{!safe?' · 未声明只读，暂不开放':''}</small></span></label>})}</fieldset>}
 <label className="agent-check"><input type="checkbox" disabled={disabled||!draft.allowed_tools.length} checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>允许归处助手在会话中调用所选工具</label><div className="agent-editor-actions"><button className="button primary" disabled={disabled||!ack}>保存连接</button><button className="button" type="button" disabled={busy} onClick={()=>setDraft(null)}>取消</button></div></form>}
 </section>
}
