import {toggleAppearance} from './theme-helpers.mjs';
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1004,height:884},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765');await page.locator('.agent-row').first().waitFor();assert.equal(await page.locator('.topbar').count(),0);await page.screenshot({path:'test-results/revision-home.png',fullPage:true});
await page.locator('.agent-row').first().click();await page.locator('.object-preview').click();await page.locator('.object-drawer').waitFor();await page.getByRole('button',{name:/关联 \d/}).click();await page.locator('.relation-row').first().click();await page.getByRole('button',{name:'返回',exact:true}).click();assert(await page.locator('.relation-row').count()>0);await page.getByRole('button',{name:'备注',exact:true}).click();await page.getByLabel('备注',{exact:true}).fill('抽屉草稿验证');await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelector('.object-preview')===document.activeElement);await page.locator('.agent-row').first().click();await page.locator('.object-preview').click();assert.equal(await page.getByLabel('备注',{exact:true}).inputValue(),'抽屉草稿验证');
await page.getByRole('button',{name:'概览',exact:true}).click();await page.screenshot({path:'test-results/revision-drawer.png',fullPage:true});await page.keyboard.press('Escape');await toggleAppearance(page);await page.screenshot({path:'test-results/revision-dark.png',fullPage:true});await toggleAppearance(page);
await page.locator('.sidebar-search button').click();await page.getByRole('textbox',{name:'搜索所有对象'}).fill('tavily');await page.locator('.command-results button').first().click();await page.locator('.object-preview').click();await page.locator('.object-drawer').waitFor();await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'打开导航'}).click();await page.locator('.nav-item').filter({hasText:'工作台'}).click();await page.screenshot({path:'test-results/revision-mobile.png',fullPage:true});await page.locator('.agent-row').first().click();await page.locator('.object-preview').click();await page.screenshot({path:'test-results/revision-mobile-drawer.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await browser.close();console.log('PASS drawer hierarchy, focus return, draft, search, desktop/dark/mobile');
