import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1360,height:1000},reducedMotion:'reduce'}),errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));
 let testFailed=false,saveFailed=false;let data={active_id:'one',providers:[{id:'one',name:'当前连接',key_configured:true,config:{endpoint:'https://example.invalid/v1',model:'model-a',max_output_tokens:2048,timeout:60,max_tool_calls:8,max_requests:4},models:[{id:'model-a',name:'通用模型'}]},{id:'two',name:'备用连接',key_configured:false,config:{endpoint:'https://second.invalid/v1',model:'model-b'},models:[{id:'model-b',name:'备用模型'}]}]};
 await page.route('**/api/model/catalog',async route=>{const b=route.request().postDataJSON();calls.push(b);if(b.action==='save'&&saveFailed){await route.fulfill({status:409,json:{error:'模拟保存冲突，请重试。'}});return}let result=data;if(b.action==='save'){const p={id:b.id||'new',name:b.name,config:b.config,models:b.models,key_configured:!!b.api_key||(!b.clear_key&&data.providers.find(p=>p.id===b.id)?.key_configured)};data={...data,providers:[...data.providers.filter(x=>x.id!==p.id),p]};result=data}else if(b.action==='models')result={models:[{id:'model-a',name:'通用模型'},{id:'model-c',name:'推理模型'},{id:'model-d',name:'视觉模型'}]};else if(b.action==='activate'){data={...data,active_id:b.id};result=data}else if(b.action==='delete'){data={...data,providers:data.providers.filter(p=>p.id!==b.id)};result=data}else if(b.action==='test')result=testFailed?{ok:false,message:'模拟连接失败'}:{ok:true};await route.fulfill({json:result})});
 await page.goto('http://127.0.0.1:8765');await page.getByRole('button',{name:'设置',exact:true}).click();await expect(page.getByText('当前使用',{exact:true})).toBeVisible();await page.screenshot({path:'test-results/model-catalog-desktop.png'});
 const row=name=>page.locator('.provider-item').filter({has:page.getByText(name,{exact:true})});
 await row('当前连接').getByRole('button',{name:'编辑',exact:true}).click();await expect(page.getByLabel('API 密钥',{exact:true})).toHaveValue('');await page.getByLabel('提供商名称',{exact:true}).fill('草稿名称');await page.getByRole('tab',{name:'检查来源'}).click();await page.getByRole('tab',{name:'模型连接'}).click();await expect(page.getByLabel('提供商名称',{exact:true})).toHaveValue('草稿名称');
 await row('备用连接').getByRole('button',{name:'编辑',exact:true}).click();await page.getByRole('button',{name:'返回编辑',exact:true}).click();await expect(page.getByLabel('提供商名称',{exact:true})).toHaveValue('草稿名称');await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'放弃修改',exact:true}).click();assert.equal(calls.filter(c=>c.action==='save').length,0);
 await row('当前连接').getByRole('button',{name:'编辑',exact:true}).click();await page.getByRole('button',{name:'获取可用模型',exact:true}).click();await page.getByLabel('搜索模型').fill('推理');await page.getByRole('checkbox',{name:'推理模型 model-c'}).check();await page.screenshot({path:'test-results/model-catalog-picker.png'});await page.getByRole('button',{name:'添加所选（1）'}).click();await page.getByRole('radio',{name:'默认模型 model-c',exact:true}).check();await page.getByLabel('API 密钥',{exact:true}).fill('mock-secret');await page.screenshot({path:'test-results/model-catalog-editor.png'});await page.getByRole('button',{name:'保存提供商',exact:true}).click();assert.equal(calls.find(c=>c.action==='save').config.model,'model-c');
 await row('当前连接').getByRole('button',{name:'编辑',exact:true}).click();await expect(page.getByLabel('API 密钥',{exact:true})).toHaveValue('');await page.getByRole('button',{name:'测试连接',exact:true}).click();await expect(row('当前连接').getByText(/本次测试通过/)).toBeVisible();testFailed=true;await page.getByRole('button',{name:'测试连接',exact:true}).click();await expect(page.getByRole('alert')).toContainText('模拟连接失败');await expect(row('当前连接').getByText(/本次测试通过/)).toHaveCount(0);await page.getByRole('button',{name:'取消',exact:true}).click();await row('备用连接').getByRole('button',{name:'使用',exact:true}).click();await row('当前连接').getByRole('button',{name:'删除提供商 当前连接',exact:true}).click();await page.getByRole('button',{name:'确认删除',exact:true}).click();await expect(page.getByText('当前连接',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'添加模型提供商',exact:true}).click();await page.getByLabel('提供商名称',{exact:true}).fill('新连接');await page.getByLabel('接口地址',{exact:true}).fill('https://new.invalid/v1');await page.getByRole('button',{name:'手工添加模型',exact:true}).click();await page.getByLabel('模型标识 1',{exact:true}).fill('new-model');await page.getByLabel('显示名称 1',{exact:true}).fill('新模型');await page.getByRole('radio',{name:'默认模型 new-model',exact:true}).check();saveFailed=true;await page.getByRole('button',{name:'保存提供商',exact:true}).click();await expect(page.getByRole('alert')).toContainText('模拟保存冲突');await expect(page.getByLabel('提供商名称',{exact:true})).toHaveValue('新连接');saveFailed=false;await page.getByRole('button',{name:'保存提供商',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await row('新连接').getByRole('button',{name:'编辑',exact:true}).click();await page.screenshot({path:'test-results/model-catalog-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByRole('button',{name:'获取可用模型',exact:true}).click();await page.screenshot({path:'test-results/model-catalog-mobile-picker.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByRole('button',{name:'取消',exact:true}).click();await page.route('**/api/state',route=>route.abort());await expect(page.getByText('本地服务离线，连接恢复后可继续设置。',{exact:true})).toBeVisible({timeout:8000});await expect(page.getByRole('button',{name:'保存提供商',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'获取可用模型',exact:true})).toBeDisabled();assert.deepEqual(errors,[]);console.log('PASS catalog list/edit/add/default/fetch/search/save/activate/delete/test, dirty guard, category persistence, secret reset, desktop/mobile; all catalog requests mocked');
}finally{await browser.close()}
