import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1435,height:920},reducedMotion:'reduce'}),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{localStorage.removeItem('desk-appearance');localStorage.setItem('desk-theme','light')});
 await page.route('**/api/**',async route=>{if(route.request().method()!=='POST')return route.continue();const path=new URL(route.request().url()).pathname;writes.push(path);const results={'/api/assistant/list':{sessions:[]},'/api/model/settings':{config:{}},'/api/model/catalog':{providers:[],active_id:null},'/api/source/list':{sources:[]},'/api/mcp-action/list':{actions:[]}};return route.fulfill(results[path]?{json:results[path]}:{status:400,json:{error:'Unexpected mocked request '+path}})});
 await page.goto('http://127.0.0.1:8765');await page.getByRole('button',{name:'选择主题',exact:true}).click();const dialog=page.getByRole('dialog',{name:'外观主题',exact:true});await expect(dialog).toBeFocused();await expect(page.locator('.theme-wheel-overlay')).toHaveCount(0);await expect(dialog.locator('.theme-wheel-swatch:visible')).toHaveCount(3);let bounds=await dialog.boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=1435&&bounds.y>=0&&bounds.y+bounds.height<=920);
 await page.keyboard.press('ArrowRight');await expect(dialog.locator('.theme-browsed-name')).toHaveText('雾蓝');await expect(page.locator('html')).toHaveAttribute('data-palette','mist');await page.keyboard.press('Enter');await expect(page.locator('html')).toHaveAttribute('data-palette','mist');await page.keyboard.press('Control+k');await expect(page.locator('.command-dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'应用燕麦陶红',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-palette','oat');await dialog.focus();await page.mouse.move(bounds.x+80,bounds.y+80);const wheelBefore=await dialog.locator('.theme-browsed-name').textContent(),scrollBefore=await page.evaluate(()=>scrollY);await page.mouse.wheel(0,70);await expect(dialog.locator('.theme-browsed-name')).not.toHaveText(wheelBefore);assert.equal(await page.evaluate(()=>scrollY),scrollBefore);await expect.poll(()=>page.evaluate(()=>DeskThemes.themes.find(t=>t.name===document.querySelector('.theme-browsed-name').textContent).id===document.documentElement.dataset.palette)).toBe(true);const beforeDrag=await dialog.locator('.theme-browsed-name').textContent();await page.mouse.move(bounds.x+80,bounds.y+80);await page.mouse.down();await page.mouse.move(bounds.x+260,bounds.y+180,{steps:8});await page.mouse.up();assert.notEqual(await dialog.locator('.theme-browsed-name').textContent(),beforeDrag);await expect.poll(()=>page.evaluate(()=>DeskThemes.themes.find(t=>t.name===document.querySelector('.theme-browsed-name').textContent).id===document.documentElement.dataset.palette)).toBe(true);await dialog.focus();await page.keyboard.press('Home');await expect(dialog.locator('.theme-wheel-swatch:visible')).toHaveCount(3);await page.screenshot({path:'test-results/theme-quarter-1435-light.png'});await page.getByRole('button',{name:'深色',exact:true}).click();await page.screenshot({path:'test-results/theme-quarter-1435-dark.png'});await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'选择主题',exact:true})).toBeFocused();
 await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('tab',{name:'外观'}).click();await expect(page.locator('.appearance-settings')).toContainText('松绿');await page.locator('.appearance-settings').getByRole('button',{name:'跟随系统',exact:true}).click();await page.emulateMedia({colorScheme:'light'});await expect(page.locator('html')).toHaveAttribute('data-theme','light');await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.locator('.appearance-settings').getByRole('button',{name:'浅色',exact:true}).click();
 for(const width of [990,390]){await page.setViewportSize({width,height:width===390?844:920});await page.locator('.appearance-settings').getByRole('button',{name:'选择主题',exact:true}).click();await expect(dialog).toBeFocused();await expect(dialog.locator('.theme-wheel-swatch:visible')).toHaveCount(3);bounds=await dialog.boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=width&&bounds.y>=0&&bounds.y+bounds.height<=(width===390?844:920));await page.keyboard.press('End');await page.keyboard.press('Enter');await expect(page.locator('html')).toHaveAttribute('data-palette','graphite');await page.getByRole('button',{name:'浅色',exact:true}).last().click();await page.screenshot({path:`test-results/theme-quarter-${width}-light.png`});await page.getByRole('button',{name:'深色',exact:true}).last().click();await page.screenshot({path:`test-results/theme-quarter-${width}-dark.png`});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.mouse.click(width-15,90);await expect(dialog).toHaveCount(0);await expect(page.locator('.appearance-settings').getByRole('button',{name:'选择主题',exact:true})).toBeFocused();}
 const contrast=await page.evaluate(()=>{const lum=hex=>{const a=hex.match(/[0-9a-f]{2}/gi).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722};const ratio=(a,b)=>{const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)};return DeskThemes.themes.flatMap(t=>['light','dark'].flatMap(mode=>{const c=DeskThemes.tokens(t.id,mode);return [['ink','surface'],['muted','surface'],['muted','soft'],['accent','surface'],['accent','soft'],['on-accent','accent'],['nav-muted','nav'],['nav-active-ink','nav-active'],['success','surface'],['warning','warning-bg']].map(([a,b])=>({theme:t.id,mode,pair:a+'/'+b,ratio:ratio(c[a],c[b])}))}))});assert(contrast.every(r=>r.ratio>=4.5),JSON.stringify(contrast.filter(r=>r.ratio<4.5)));await writeFile('test-results/theme-contrast.json',JSON.stringify(contrast,null,2));
 await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw Error('blocked')}});await page.locator('.appearance-settings').getByRole('button',{name:'浅色',exact:true}).click();await expect(page.locator('.appearance-settings').getByRole('status')).toContainText('本次未能保存');await expect(page.locator('html')).toHaveAttribute('data-theme','light');assert.deepEqual(errors,[]);assert(!writes.some(p=>/run\/start|\/save|\/confirm/.test(p)));console.log('PASS theme browse auto-apply, drag/wheel/keyboard/click, system live changes, settings sync, Radix focus/esc, storage failure, 120 contrast pairs, desktop/mobile; all POST mocked');
 const first=await browser.newPage();await first.addInitScript(()=>{localStorage.removeItem('desk-appearance');localStorage.setItem('desk-theme','dark')});await first.route('**/assets/*.js',route=>route.abort());await first.goto('http://127.0.0.1:8765');await expect(first.locator('html')).toHaveAttribute('data-theme','dark');await expect(first.locator('html')).toHaveAttribute('data-palette','pine');console.log('PASS legacy dark applied before React asset loads');const blocked=await browser.newPage();await blocked.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('blocked')}});await blocked.route('**/assets/*.js',route=>route.abort());await blocked.goto('http://127.0.0.1:8765');await expect(blocked.locator('html')).toHaveAttribute('data-theme','light');await expect(blocked.locator('html')).toHaveAttribute('data-palette','pine');console.log('PASS startup storage denial safely falls back');
}finally{await browser.close()}
